/**
 * Miro Developer Platform
 * <img src=\"https://content.pstmn.io/47449ea6-0ef7-4af2-bac1-e58a70e61c58/aW1hZ2UucG5n\" width=\"1685\" height=\"593\">  ### Miro Developer Platform concepts  - New to the Miro Developer Platform? Interested in learning more about platform concepts?? [Read our introduction page](https://beta.developers.miro.com/docs/introduction) and familiarize yourself with the Miro Developer Platform capabilities in a few minutes.   ### Getting started with the Miro REST API  - [Quickstart (video):](https://beta.developers.miro.com/docs/try-out-the-rest-api-in-less-than-3-minutes) try the REST API in less than 3 minutes. - [Quickstart (article):](https://beta.developers.miro.com/docs/build-your-first-hello-world-app-1) get started and try the REST API in less than 3 minutes.   ### Miro REST API tutorials  Check out our how-to articles with step-by-step instructions and code examples so you can:  - [Get started with OAuth 2.0 and Miro](https://beta.developers.miro.com/docs/getting-started-with-oauth)   ### Miro App Examples  Clone our [Miro App Examples repository](https://github.com/miroapp/app-examples) to get inspiration, customize, and explore apps built on top of Miro\'s Developer Platform 2.0.
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {AiInteractionLogActor} from './aiInteractionLogActor'
import {AiInteractionLogModel} from './aiInteractionLogModel'
import {AiInteractionLogObject} from './aiInteractionLogObject'
import {AiInteractionLogSession} from './aiInteractionLogSession'
import {AiInteractionLogTool} from './aiInteractionLogTool'

/**
 * @internal
 * Contains information about a single AI interaction event. One conversation produces several events that share the same <code>session.id</code>, and one request together with its response share the same <code>turnId</code>.
 */
export class AiInteractionLog {
  /**
   * Unique identifier of the AI interaction log entry.
   */
  'id'?: string
  /**
   * Date and time when the AI interaction occurred.<br>Format: UTC, adheres to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), includes a [trailing Z offset](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)).
   */
  'createdAt'?: Date
  /**
   * Date and time when the AI interaction log was stored.<br>Format: UTC, adheres to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), includes a [trailing Z offset](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)).
   */
  'storedAt'?: Date
  'session'?: AiInteractionLogSession
  /**
   * Where in Miro the interaction started: the entry point the user acted through, for example Sidekick chat, an AI Flow, or an MCP call. It is not the AI capability that ran, since one surface can invoke many features. Events not yet attributed to a specific surface arrive as <code>unspecified</code>. Read it as a string rather than a fixed list, because values are added as more entry points are covered.
   */
  'surface'?: string
  'actor'?: AiInteractionLogActor
  'object'?: AiInteractionLogObject
  /**
   * Step of the interaction this entry records: <ul> <li><code>input</code>: the request that opened the turn, as received, before any processing. In a conversation this is the person\'s prompt; for automated features it is the request that triggered the work.</li> <li><code>model_invocation_request</code>: what was sent to the model, including context and conversation history the AI added.</li> <li><code>model_invocation_response</code>: what the model returned.</li> <li><code>tool_invocation_request</code>: a tool the AI decided to call, and the arguments it passed.</li> <li><code>tool_invocation_response</code>: the outcome of that tool call.</li> <li><code>output</code>: the final response returned for that request. In a conversation this is what the person was shown.</li> </ul> Not all events are produced for every interaction: some carry only model events, some only tool events. New event types may be added, so ignore a type you do not recognise rather than treating it as an error.
   */
  'eventType'?: string
  /**
   * Groups the events of one exchange: a single user request, everything the AI did to handle it (model calls and tool calls), and the response returned to the user. A conversation is a sequence of turns; every event of one turn shares a <code>turnId</code>.
   */
  'turnId'?: string
  /**
   * Additional details about the AI interaction. The structure of this object varies depending on the event type. The text may contain unstructured data that could reveal information used in interactions with the LLM. The example below is a <code>model_invocation_response</code>.
   */
  'details'?: {[key: string]: any}
  'model'?: AiInteractionLogModel
  'tool'?: AiInteractionLogTool

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'storedAt',
      baseName: 'storedAt',
      type: 'Date',
    },
    {
      name: 'session',
      baseName: 'session',
      type: 'AiInteractionLogSession',
    },
    {
      name: 'surface',
      baseName: 'surface',
      type: 'string',
    },
    {
      name: 'actor',
      baseName: 'actor',
      type: 'AiInteractionLogActor',
    },
    {
      name: 'object',
      baseName: 'object',
      type: 'AiInteractionLogObject',
    },
    {
      name: 'eventType',
      baseName: 'eventType',
      type: 'string',
    },
    {
      name: 'turnId',
      baseName: 'turnId',
      type: 'string',
    },
    {
      name: 'details',
      baseName: 'details',
      type: '{ [key: string]: any; }',
    },
    {
      name: 'model',
      baseName: 'model',
      type: 'AiInteractionLogModel',
    },
    {
      name: 'tool',
      baseName: 'tool',
      type: 'AiInteractionLogTool',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return AiInteractionLog.attributeTypeMap
  }
}
