/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {CustomField} from './customField'

/**
 * @internal
 * Contains app card item data, such as the title, description, or fields.
 */
export class AppCardData {
  /**
   * A short text description to add context about the app card.
   */
  'description'?: string
  /**
   * Array where each object represents a custom preview field. Preview fields are displayed on the bottom half of the app card in the compact view.
   */
  'fields'?: Array<CustomField>
  /**
   * Status indicating whether an app card is connected and in sync with the source. When the source for the app card is deleted, the status returns `disabled`.
   */
  'status'?: string | (typeof AppCardData.StatusEnum)[keyof typeof AppCardData.StatusEnum] =
    AppCardData.StatusEnum.Disconnected
  /**
   * A short text header to identify the app card.
   */
  'title'?: string = 'sample app card item'

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'description',
      baseName: 'description',
      type: 'string',
    },
    {
      name: 'fields',
      baseName: 'fields',
      type: 'Array<CustomField>',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'AppCardData.StatusEnum',
    },
    {
      name: 'title',
      baseName: 'title',
      type: 'string',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return AppCardData.attributeTypeMap
  }
}

export namespace AppCardData {
  export const StatusEnum = {
    Disconnected: 'disconnected',
    Connected: 'connected',
    Disabled: 'disabled',
  } as const
}
