/**
 * Miro Developer Platform
 * <img src=\"https://content.pstmn.io/47449ea6-0ef7-4af2-bac1-e58a70e61c58/aW1hZ2UucG5n\" width=\"1685\" height=\"593\">  ### Miro Developer Platform concepts  - New to the Miro Developer Platform? Interested in learning more about platform concepts?? [Read our introduction page](https://beta.developers.miro.com/docs/introduction) and familiarize yourself with the Miro Developer Platform capabilities in a few minutes.   ### Getting started with the Miro REST API  - [Quickstart (video):](https://beta.developers.miro.com/docs/try-out-the-rest-api-in-less-than-3-minutes) try the REST API in less than 3 minutes. - [Quickstart (article):](https://beta.developers.miro.com/docs/build-your-first-hello-world-app-1) get started and try the REST API in less than 3 minutes.   ### Miro REST API tutorials  Check out our how-to articles with step-by-step instructions and code examples so you can:  - [Get started with OAuth 2.0 and Miro](https://beta.developers.miro.com/docs/getting-started-with-oauth)   ### Miro App Examples  Clone our [Miro App Examples repository](https://github.com/miroapp/app-examples) to get inspiration, customize, and explore apps built on top of Miro\'s Developer Platform 2.0.
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {CreateUserResourceName} from './createUserResourceName'
import {CreateUserResourcePhotosInner} from './createUserResourcePhotosInner'
import {CreateUserResourceRolesInner} from './createUserResourceRolesInner'
import {CreateUserResourceUrnIetfParamsScimSchemasExtensionEnterprise20User} from './createUserResourceUrnIetfParamsScimSchemasExtensionEnterprise20User'

export class CreateUserResource {
  /**
   * Identifies which schema(s) this resource uses. In this case it is the SCIM core User schema.
   */
  'schemas'?: Array<string>
  /**
   * The unique username/login identifier. An email address in this case. <br><br> Note: Payload must include the userName attribute populated with an email address<br><br> User is created with this email address in the organization. This attribute will be used as full name of the created user if the displayName or name attribute is not provided.
   */
  'userName': string
  'name'?: CreateUserResourceName
  /**
   * A human-readable name for the user, typically the full name. This attribute is used if the value is not empty. <br><br> Maximum length: 60 characters
   */
  'displayName'?: string
  /**
   * Free-form string to indicate the user license type in the organization. <br><br> Only supported values for licenses are allowed. Supported licences for organizations can vary. They can potentially have the following values: Full, Free, Free Restricted, Full (Trial), Basic. <br><br> Note: When `userType` is specified, the `userType` license is set per the value provided. When `userType` is not specified, the user license is set according to internal Miro logic, which depends on the organization plan.
   */
  'userType'?: string
  /**
   * Indicates whether the user is active or deactivated in the organization.
   */
  'active'?: boolean
  /**
   * An array of display picture for the user in the organization. Contains photo value and type. <br><br> Notes: Must be a text URL to the image. Supported file types: jpg, jpeg, bmp, png, gif. <br><br> To define file type, you should have defined file extension in url (e.g. https://host.com/avatar_user1.jpg) or request to url should return together with a file content a header Content-Type (e.g. Content-Type = image/jpeg) <br><br> Maximum file size to download is: 31457280 bytes. <br><br> Example (Okta): photos.^[type==photo].value <br> Example (Azure): photos[type eq \"photo\"].value
   */
  'photos'?: Array<CreateUserResourcePhotosInner>
  /**
   * An array of roles assigned to the user in the organization. Contains role value, display, type, and primary flag. <br><br> organization_user_role supported values include: ORGANIZATION_INTERNAL_ADMIN and ORGANIZATION_INTERNAL_USER. organization_admin_role supported values include: Content Admin, User Admin, Security Admin, or names of custom admin roles. <br><br> Example (Okta) for organization_user_role: roles.^[primary==true].value <br> Example (Azure) for organization_user_role: roles[primary eq \"True\"].value <br> Example (Okta) for organization_admin_role: roles.^[primary==false].value <br> Example (Azure) for organization_admin_role: roles[primary eq \"False\"].value <br>
   */
  'roles'?: Array<CreateUserResourceRolesInner>
  /**
   * Specifies the user\'s preferred language. <br><br> Example: en_US for English.
   */
  'preferredLanguage'?: string
  'urnietfparamsscimschemasextensionenterprise20User'?: CreateUserResourceUrnIetfParamsScimSchemasExtensionEnterprise20User

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'schemas',
      baseName: 'schemas',
      type: 'Array<CreateUserResource.SchemasEnum>',
    },
    {
      name: 'userName',
      baseName: 'userName',
      type: 'string',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'CreateUserResourceName',
    },
    {
      name: 'displayName',
      baseName: 'displayName',
      type: 'string',
    },
    {
      name: 'userType',
      baseName: 'userType',
      type: 'string',
    },
    {
      name: 'active',
      baseName: 'active',
      type: 'boolean',
    },
    {
      name: 'photos',
      baseName: 'photos',
      type: 'Array<CreateUserResourcePhotosInner>',
    },
    {
      name: 'roles',
      baseName: 'roles',
      type: 'Array<CreateUserResourceRolesInner>',
    },
    {
      name: 'preferredLanguage',
      baseName: 'preferredLanguage',
      type: 'string',
    },
    {
      name: 'urnietfparamsscimschemasextensionenterprise20User',
      baseName: 'urn:ietf:params:scim:schemas:extension:enterprise:2.0:User',
      type: 'CreateUserResourceUrnIetfParamsScimSchemasExtensionEnterprise20User',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return CreateUserResource.attributeTypeMap
  }
}

export namespace CreateUserResource {
  export const SchemasEnum = {
    Urnietfparamsscimschemascore20User: 'urn:ietf:params:scim:schemas:core:2.0:User',
  } as const
}
