/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @internal
 * Contains frame item data, such as the title, frame type, or frame format.
 */
export class FrameData {
  /**
   * Only custom frames are supported at the moment.
   */
  'format'?: string | (typeof FrameData.FormatEnum)[keyof typeof FrameData.FormatEnum] = FrameData.FormatEnum.Custom
  /**
   * Title of the frame. This title appears at the top of the frame.
   */
  'title'?: string
  /**
   * Only free form frames are supported at the moment.
   */
  'type'?: string | (typeof FrameData.TypeEnum)[keyof typeof FrameData.TypeEnum] = FrameData.TypeEnum.Freeform
  /**
   * Hide or reveal the content inside a frame (Enterprise plan only).
   */
  'showContent'?: boolean = true

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'format',
      baseName: 'format',
      type: 'FrameData.FormatEnum',
    },
    {
      name: 'title',
      baseName: 'title',
      type: 'string',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'FrameData.TypeEnum',
    },
    {
      name: 'showContent',
      baseName: 'showContent',
      type: 'boolean',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return FrameData.attributeTypeMap
  }
}

export namespace FrameData {
  export const FormatEnum = {
    Custom: 'custom',
    Desktop: 'desktop',
    Phone: 'phone',
    Tablet: 'tablet',
    A4: 'a4',
    Letter: 'letter',
    Ratio1x1: 'ratio_1x1',
    Ratio4x3: 'ratio_4x3',
    Ratio16x9: 'ratio_16x9',
  } as const
  export const TypeEnum = {
    Freeform: 'freeform',
    Heap: 'heap',
    Grid: 'grid',
    Rows: 'rows',
    Columns: 'columns',
  } as const
}
