/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {Geometry} from './geometry'
import {ItemDataChanges} from './itemDataChanges'
import {ItemStyle} from './itemStyle'
import {ItemTypeChange} from './itemTypeChange'
import {ParentPlatformBulkCreateOperationExperimentalRelease} from './parentPlatformBulkCreateOperationExperimentalRelease'
import {PositionChangePlatformBulkCreateOperationExperimentalRelease} from './positionChangePlatformBulkCreateOperationExperimentalRelease'

/**
 * @internal
 * Updates one or more items in one request. You can update up to 20 items per request.
 */
export class ItemChanges {
  /**
   * Unique identifier (ID) of an item.
   */
  'id'?: string
  'type'?: ItemTypeChange
  'data'?: ItemDataChanges
  'style'?: ItemStyle
  'position'?: PositionChangePlatformBulkCreateOperationExperimentalRelease
  'geometry'?: Geometry
  'parent'?: ParentPlatformBulkCreateOperationExperimentalRelease

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'ItemTypeChange',
    },
    {
      name: 'data',
      baseName: 'data',
      type: 'ItemDataChanges',
    },
    {
      name: 'style',
      baseName: 'style',
      type: 'ItemStyle',
    },
    {
      name: 'position',
      baseName: 'position',
      type: 'PositionChangePlatformBulkCreateOperationExperimentalRelease',
    },
    {
      name: 'geometry',
      baseName: 'geometry',
      type: 'Geometry',
    },
    {
      name: 'parent',
      baseName: 'parent',
      type: 'ParentPlatformBulkCreateOperationExperimentalRelease',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return ItemChanges.attributeTypeMap
  }
}
