/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {CreatedBy} from './createdBy'
import {Geometry} from './geometry'
import {ItemData} from './itemData'
import {ItemStyle} from './itemStyle'
import {ModifiedBy} from './modifiedBy'
import {ParentWithLinks} from './parentWithLinks'
import {PositionPlatformBulkCreateOperationExperimentalRelease} from './positionPlatformBulkCreateOperationExperimentalRelease'
import {SelfLinkPlatformBulkCreateOperationExperimentalRelease} from './selfLinkPlatformBulkCreateOperationExperimentalRelease'

/**
 * @internal
 * Contains information about an item.
 */
export class Item {
  /**
   * Unique identifier (ID) of an item.
   */
  'id': string
  'data'?: ItemData
  'style'?: ItemStyle
  'position'?: PositionPlatformBulkCreateOperationExperimentalRelease
  'geometry'?: Geometry
  'parent'?: ParentWithLinks
  'isSupported'?: boolean
  'createdBy'?: CreatedBy
  /**
   * Date and time when the item was created. <br>Format: UTC, adheres to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), includes a [trailing Z offset](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)).
   */
  'createdAt'?: Date
  'modifiedBy'?: ModifiedBy
  /**
   * Date and time when the item was last modified. <br>Format: UTC, adheres to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), includes a [trailing Z offset](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)).
   */
  'modifiedAt'?: Date
  'links': SelfLinkPlatformBulkCreateOperationExperimentalRelease

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'data',
      baseName: 'data',
      type: 'ItemData',
    },
    {
      name: 'style',
      baseName: 'style',
      type: 'ItemStyle',
    },
    {
      name: 'position',
      baseName: 'position',
      type: 'PositionPlatformBulkCreateOperationExperimentalRelease',
    },
    {
      name: 'geometry',
      baseName: 'geometry',
      type: 'Geometry',
    },
    {
      name: 'parent',
      baseName: 'parent',
      type: 'ParentWithLinks',
    },
    {
      name: 'isSupported',
      baseName: 'isSupported',
      type: 'boolean',
    },
    {
      name: 'createdBy',
      baseName: 'createdBy',
      type: 'CreatedBy',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'Date',
    },
    {
      name: 'modifiedBy',
      baseName: 'modifiedBy',
      type: 'ModifiedBy',
    },
    {
      name: 'modifiedAt',
      baseName: 'modifiedAt',
      type: 'Date',
    },
    {
      name: 'links',
      baseName: 'links',
      type: 'SelfLinkPlatformBulkCreateOperationExperimentalRelease',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return Item.attributeTypeMap
  }
}
