/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {OrganizationInformation} from './organizationInformation'
import {TeamInformation} from './teamInformation'
import {UserInformation} from './userInformation'

export class TokenInformation {
  'type': string
  'organization'?: OrganizationInformation
  'team': TeamInformation
  'createdBy': UserInformation
  'user': UserInformation
  'scopes'?: Array<string>

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'type',
      baseName: 'type',
      type: 'string',
    },
    {
      name: 'organization',
      baseName: 'organization',
      type: 'OrganizationInformation',
    },
    {
      name: 'team',
      baseName: 'team',
      type: 'TeamInformation',
    },
    {
      name: 'createdBy',
      baseName: 'createdBy',
      type: 'UserInformation',
    },
    {
      name: 'user',
      baseName: 'user',
      type: 'UserInformation',
    },
    {
      name: 'scopes',
      baseName: 'scopes',
      type: 'Array<string>',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return TokenInformation.attributeTypeMap
  }
}
