/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Team picture
*/
export class CreatePictureRequest {
    /**
    * Original team picture url for icon generation. Note: picture update is not supported yet.
    */
    'originalUrl'?: string;

    /** @ignore */
    static discriminator: string | undefined = undefined;

    /** @ignore */
    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "originalUrl",
            "baseName": "originalUrl",
            "type": "string"
        }    ];

    /** @ignore */
    static getAttributeTypeMap() {
        return CreatePictureRequest.attributeTypeMap;
    }
}

