/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {Tag} from './tag'

export class GetTagsResponse {
  'tags'?: Array<Tag>

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<Tag>',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return GetTagsResponse.attributeTypeMap
  }
}
