/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {FixedRatioGeometry} from './fixedRatioGeometry'
import {ImageUrlData} from './imageUrlData'
import {Parent} from './parent'
import {PositionChange} from './positionChange'

export class ImageCreateRequest {
  'data': ImageUrlData
  'position'?: PositionChange
  'geometry'?: FixedRatioGeometry
  'parent'?: Parent

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'data',
      baseName: 'data',
      type: 'ImageUrlData',
    },
    {
      name: 'position',
      baseName: 'position',
      type: 'PositionChange',
    },
    {
      name: 'geometry',
      baseName: 'geometry',
      type: 'FixedRatioGeometry',
    },
    {
      name: 'parent',
      baseName: 'parent',
      type: 'Parent',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return ImageCreateRequest.attributeTypeMap
  }
}
