/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Tag {
  /**
   * Background color of the tag. Possible values: `red`, `light_green`, `cyan`, `yellow`, `magenta`, `green`, `blue`, `gray`, `violet`, `dark_green`, `dark_blue`, `black`
   */
  'fillColor'?: Tag.FillColorEnum
  /**
   * Unique identifier of the tag.
   */
  'id'?: number
  /**
   * Text of the tag
   */
  'title'?: string
  /**
   * Type of the object that is returned. In this case, type returns `tag`.
   */
  'type'?: string

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'fillColor',
      baseName: 'fillColor',
      type: 'Tag.FillColorEnum',
    },
    {
      name: 'id',
      baseName: 'id',
      type: 'number',
    },
    {
      name: 'title',
      baseName: 'title',
      type: 'string',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'string',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return Tag.attributeTypeMap
  }
}

export namespace Tag {
  export enum FillColorEnum {
    Red = <any>'red',
    LightGreen = <any>'light_green',
    Cyan = <any>'cyan',
    Yellow = <any>'yellow',
    Magenta = <any>'magenta',
    Green = <any>'green',
    Blue = <any>'blue',
    Gray = <any>'gray',
    Violet = <any>'violet',
    DarkGreen = <any>'dark_green',
    DarkBlue = <any>'dark_blue',
    Black = <any>'black',
  }
}
