/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class TagCreateRequest {
  /**
   * [Fill color for the tag](https://developers.miro.com/reference/rest-api-tag-data-model) Possible values: `red`, `light_green`, `cyan`, `yellow`, `magenta`, `green`, `blue`, `gray`, `violet`, `dark_green`, `dark_blue`, `black`
   */
  'fillColor'?: string | typeof TagCreateRequest.FillColorEnum[keyof typeof TagCreateRequest.FillColorEnum] =
    TagCreateRequest.FillColorEnum.Red
  /**
   * [Text of the tag](https://developers.miro.com/reference/rest-api-tag-data-model)
   */
  'title': string

  /** @ignore */
  static discriminator: string | undefined = undefined

  /** @ignore */
  static attributeTypeMap: Array<{name: string; baseName: string; type: string}> = [
    {
      name: 'fillColor',
      baseName: 'fillColor',
      type: 'TagCreateRequest.FillColorEnum',
    },
    {
      name: 'title',
      baseName: 'title',
      type: 'string',
    },
  ]

  /** @ignore */
  static getAttributeTypeMap() {
    return TagCreateRequest.attributeTypeMap
  }
}

export namespace TagCreateRequest {
  export const FillColorEnum = {
    Red: 'red',
    LightGreen: 'light_green',
    Cyan: 'cyan',
    Yellow: 'yellow',
    Magenta: 'magenta',
    Green: 'green',
    Blue: 'blue',
    Gray: 'gray',
    Violet: 'violet',
    DarkGreen: 'dark_green',
    DarkBlue: 'dark_blue',
    Black: 'black',
  } as const
}
