openapi: 3.0.3
info:
  title: Enterprise User Sessions Expiration (Enterprise Plan)
  version: v2
servers:
- url: https://api.miro.com
security:
- bearerAuth: []
tags:
- description: Delete all sessions
  name: User Sessions
paths:
  /v2/sessions/reset_all:
    post:
      description: Delete all user sessions.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">sessions:delete</a> <br/><h3>Rate limiting</h3> <a
        target="blank" href="/reference/ratelimiting">Level 3</a> <br/><h3>Enterprise
        only</h3> <p>This API is available only for <a target="blank" href="/reference/api-reference#enterprise-plan">Enterprise
        plan</a> users. You can only use this endpoint if you have the role of a Company
        Admin. This API is only available for preconfigured organizations. You can
        request temporary access to Enterprise APIs using <a target="_blank" href="https://miro-survey.typeform.com/to/BVPTNWJ9">this
        form</a>.</p>
      operationId: enterprise-post-user-sessions-reset
      parameters:
      - in: query
        name: email
        required: true
        description: 'Emails of the users for whom you want to delete the sessions.
          Example: `email=john.smith@example.com`'
        example: john.smith@example.com
        schema:
          type: string
      responses:
        '200':
          description: User Sessions Deleted
          content: {}
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '429':
          $ref: '#/components/responses/429'
      summary: Delete user sessions
      tags:
      - User sessions
components:
  schemas:
    BasicError:
      type: object
      properties:
        status:
          type: number
          description: HTTP status code.
        code:
          type: string
          description: Description of the status code.
        message:
          type: string
          description: Explanation for the error
        type:
          type: string
          description: Type of the object returned.
          default: error
  responses:
    '400':
      description: Malformed request
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/BasicError'
            - type: object
              properties:
                status:
                  default: 400
                code:
                  default: invalidParameters
    '401':
      description: Invalid authentication credentials
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/BasicError'
            - type: object
              properties:
                status:
                  default: 401
                code:
                  default: tokenNotProvided
    '403':
      description: Invalid access
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/BasicError'
            - type: object
              properties:
                status:
                  default: 403
                code:
                  default: forbiddenAccess
    '404':
      description: Invalid access
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/BasicError'
            - type: object
              properties:
                status:
                  default: 404
                code:
                  default: notFound
    '429':
      description: Too many requests
      content:
        application/json:
          schema:
            allOf:
            - $ref: '#/components/schemas/BasicError'
            - type: object
              properties:
                status:
                  default: 429
                code:
                  default: tooManyRequests
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
