openapi: 3.0.1
info:
  title: Platform
  version: v2.0
servers:
- url: https://api.miro.com
security:
- bearerAuth: []
paths:
  /v2/boards:
    post:
      description: Creates a board with the specified name and sharing policies.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: create-board
      summary: Create board
      tags:
      - boards
    get:
      description: Retrieves a list of boards that match the search criteria provided
        in the request. If you are an Enterprise customer and a Company Admin, you
        can retrieve all boards, including all private boards (boards that haven't
        been specifically shared with you) by enabling Content Admin permissions.
        To enable Content Admin permissions, see [Content Admin permissions for Company
        Admins](https://help.miro.com/hc/en-us/articles/360012777280-Content-Admin-permissions-for-Company-Admins).
        Note that you only get results instantaneously when you filter by the `team_id`,
        `project_id`, or both the `team_id` and `project_id`. If you use any other
        filter,  you need to give a few seconds for the indexing of newly created
        boards before retrieving boards.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:read</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-boards
      summary: Get boards
      tags:
      - boards
    put:
      description: Creates a copy of an existing board. You can also update the name,
        description, sharing policy, and permissions policy for the new board in the
        request body.<br/><h3>Required scope</h3> <a target="blank" href="/reference/scopes">boards:write</a>
        <br/><h3>Rate limiting</h3> <a target="blank" href="/reference/ratelimiting">Level
        4</a><br/>
      operationId: copy-board
      summary: Copy board
      tags:
      - boards
  /v2/boards/{board_id}:
    get:
      description: Retrieves information about a board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate limiting</h3>
        <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-specific-board
      summary: Get specific board
      tags:
      - boards
    patch:
      description: Updates a specific board.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-board
      summary: Update board
      tags:
      - boards
    delete:
      description: Deletes a board.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-board
      summary: Delete board
      tags:
      - boards
  /v2/boards/{board_id}/app_cards:
    post:
      description: Adds an app card item to a board.<br/><h3>Required scope</h3> <a
        target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3>
        <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-app-card-item
      summary: Create app card item
      tags:
      - app_cards
  /v2/boards/{board_id}/app_cards/{item_id}:
    get:
      description: Retrieves information for a specific app card item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-app-card-item
      summary: Get app card item
      tags:
      - app_cards
    patch:
      description: Updates an app card item on a board based on the data and style
        properties provided in the request body.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-app-card-item
      summary: Update app card item
      tags:
      - app_cards
    delete:
      description: Deletes an app card item from a board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-app-card-item
      summary: Delete app card item
      tags:
      - app_cards
  /v2/boards/{board_id}/cards:
    post:
      description: Adds a card item to a board<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-card-item
      summary: Create card item
      tags:
      - cards
  /v2/boards/{board_id}/cards/{item_id}:
    get:
      description: Retrieves information for a specific card item on a board<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-card-item
      summary: Get card item
      tags:
      - cards
    patch:
      description: Updates a card item on a board based on the data and style properties
        provided in the request body.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-card-item
      summary: Update card item
      tags:
      - cards
    delete:
      description: Deletes a card item from the board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-card-item
      summary: Delete card item
      tags:
      - cards
  /v2/boards/{board_id}/connectors:
    post:
      description: Adds a connector to a board.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-connector
      summary: Create connector
      tags:
      - connectors
    get:
      description: 'Retrieves a list of connectors for a specific board.


        This method returns results using a cursor-based approach. A cursor-paginated
        method returns a portion of the total set of results based on the limit specified
        and a cursor that points to the next portion of the results. To retrieve the
        next portion of the collection, on your next call to the same method, set
        the `cursor` parameter equal to the `cursor` value you received in the response
        of the previous request. For example, if you set the `limit` query parameter
        to `10` and the board contains 20 objects, the first call will return information
        about the first 10 objects in the response along with a cursor parameter and
        value. In this example, let''s say the cursor parameter value returned in
        the response is `foo`. If you want to retrieve the next set of objects, on
        your next call to the same method, set the cursor parameter value to `foo`.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>'
      operationId: get-connectors
      summary: Get connectors
      tags:
      - connectors
  /v2/boards/{board_id}/connectors/{connector_id}:
    get:
      description: Retrieves information for a specific connector on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-connector
      summary: Get specific connector
      tags:
      - connectors
    patch:
      description: Updates a connector on a board based on the data and style properties
        provided in the request body.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-connector
      summary: Update connector
      tags:
      - connectors
    delete:
      description: Deletes the specified connector from the board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-connector
      summary: Delete connector
      tags:
      - connectors
  /v2/boards/{board_id}/documents:
    post:
      description: Adds a document item to a board by specifying the URL where the
        document is hosted.<br/><h3>Required scope</h3> <a target="blank" href="/reference/scopes">boards:write</a>
        <br/><h3>Rate limiting</h3> <a target="blank" href="/reference/ratelimiting">Level
        2</a><br/>
      operationId: create-document-item-using-url
      summary: Create document item using URL
      tags:
      - documents
  /v2/boards/{board_id}/documents/{item_id}:
    get:
      description: Retrieves information for a specific document item on a board<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-document-item
      summary: Get document item
      tags:
      - documents
    patch:
      description: Updates a document item on a board<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-document-item-using-url
      summary: Update document item using URL
      tags:
      - documents
    delete:
      description: Deletes a document item from the board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-document-item
      summary: Delete document item
      tags:
      - documents
  /v2/boards/{board_id}/embeds:
    post:
      description: Adds an embed item containing external content to a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-embed-item
      summary: Create embed item
      tags:
      - embeds
  /v2/boards/{board_id}/embeds/{item_id}:
    get:
      description: Retrieves information for a specific embed item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-embed-item
      summary: Get embed item
      tags:
      - embeds
    patch:
      description: Updates an embed item on a board based on the data properties provided
        in the request body.<br/><h3>Required scope</h3> <a target="blank" href="/reference/scopes">boards:write</a>
        <br/><h3>Rate limiting</h3> <a target="blank" href="/reference/ratelimiting">Level
        2</a><br/>
      operationId: update-embed-item
      summary: Update embed item
      tags:
      - embeds
    delete:
      description: Deletes an embed item from the board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-embed-item
      summary: Delete embed item
      tags:
      - embeds
  /v2/boards/{board_id}/images:
    post:
      x-settings:
        skip-tests: true
      description: Adds an image item to a board by specifying an image URL.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-image-item-using-url
      summary: Create image item using URL
      tags:
      - images
  /v2/boards/{board_id}/images/{item_id}:
    get:
      x-settings:
        skip-tests: true
      description: Retrieves information for a specific image item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-image-item
      summary: Get image item
      tags:
      - images
    patch:
      x-settings:
        skip-tests: true
      description: Updates an image item on a board.<br/><h3>Required scope</h3> <a
        target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3>
        <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-image-item-using-url
      summary: Update image item using URL
      tags:
      - images
    delete:
      x-settings:
        skip-tests: true
      description: Deletes an image item from the board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-image-item
      summary: Delete image item
      tags:
      - images
  /v2/boards/{board_id}/items:
    get:
      description: 'Retrieves a list of items for a specific board. You can retrieve
        all items on the board, a list of child items inside a parent item, or a list
        of specific types of items by specifying URL query parameter values.


        This method returns results using a cursor-based approach. A cursor-paginated
        method returns a portion of the total set of results based on the limit specified
        and a cursor that points to the next portion of the results. To retrieve the
        next portion of the collection, on your next call to the same method, set
        the `cursor` parameter equal to the `cursor` value you received in the response
        of the previous request. For example, if you set the `limit` query parameter
        to `10` and the board contains 20 objects, the first call will return information
        about the first 10 objects in the response along with a cursor parameter and
        value. In this example, let''s say the cursor parameter value returned in
        the response is `foo`. If you want to retrieve the next set of objects, on
        your next call to the same method, set the cursor parameter value to `foo`.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>'
      operationId: get-items
      summary: Get items on board
      tags:
      - items
  /v2/boards/{board_id}/items/{item_id}:
    get:
      description: Retrieves information for a specific item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-specific-item
      summary: Get specific item on board
      tags:
      - items
    patch:
      description: Updates the position or the parent of an item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-item-position-or-parent
      summary: Update item position or parent
      tags:
      - items
    delete:
      description: Deletes an item from a board.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-item
      summary: Delete item
      tags:
      - items
  /v2/boards/{board_id}/members:
    post:
      description: Shares the board and Invites new members to collaborate on a board
        by sending an invitation email. Depending on the board's Sharing policy, there
        might be various scenarios where membership in the team is required in order
        to share the board with a user.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 3</a><br/>
      operationId: share-board
      summary: Share board
      tags:
      - board_members
    get:
      description: Retrieves a pageable list of members for a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-board-members
      summary: Get all board members
      tags:
      - board_members
  /v2/boards/{board_id}/members/{board_member_id}:
    get:
      description: Retrieves information for a board member.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate limiting</h3>
        <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-specific-board-member
      summary: Get specific board member
      tags:
      - board_members
    patch:
      description: Updates the role of a board member.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-board-member
      summary: Update board member
      tags:
      - board_members
    delete:
      description: Removes a board member from a board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: remove-board-member
      summary: Remove board member
      tags:
      - board_members
  /v2/boards/{board_id}/shapes:
    post:
      description: Adds a shape item to a board.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-shape-item
      summary: Create shape item
      tags:
      - shapes
  /v2/boards/{board_id}/shapes/{item_id}:
    get:
      description: Retrieves information for a specific shape item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-shape-item
      summary: Get shape item
      tags:
      - shapes
    patch:
      description: Updates a shape item on a board based on the data and style properties
        provided in the request body.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-shape-item
      summary: Update shape item
      tags:
      - shapes
    delete:
      description: Deletes a shape item from the board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-shape-item
      summary: Delete shape item
      tags:
      - shapes
  /v2/boards/{board_id}/sticky_notes:
    post:
      description: Adds a sticky note item to a board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-sticky-note-item
      summary: Create sticky note item
      tags:
      - sticky_notes
  /v2/boards/{board_id}/sticky_notes/{item_id}:
    get:
      description: Retrieves information for a specific sticky note item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-sticky-note-item
      summary: Get sticky note item
      tags:
      - sticky_notes
    patch:
      description: Updates a sticky note item on a board based on the data and style
        properties provided in the request body.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-sticky-note-item
      summary: Update sticky note item
      tags:
      - sticky_notes
    delete:
      description: Deletes a sticky note item from the board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-sticky-note-item
      summary: Delete sticky note item
      tags:
      - sticky_notes
  /v2/boards/{board_id}/texts:
    post:
      description: Adds a text item to a board.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-text-item
      summary: Create text item
      tags:
      - texts
  /v2/boards/{board_id}/texts/{item_id}:
    get:
      description: Retrieves information for a specific text item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-text-item
      summary: Get text item
      tags:
      - texts
    patch:
      description: Updates a text item on a board based on the data and style properties
        provided in the request body.<br/><h3>Required scope</h3> <a target="blank"
        href="/reference/scopes">boards:write</a> <br/><h3>Rate limiting</h3> <a target="blank"
        href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-text-item
      summary: Update text item
      tags:
      - texts
    delete:
      description: Deletes a text item from the board<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-text-item
      summary: Delete text item
      tags:
      - texts
components:
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
