openapi: 3.0.1
info:
  title: Platform Experimental Features
  version: v2.0
x-settings:
  skip-tests: true
servers:
- url: https://api.miro.com
security:
- bearerAuth: []
paths:
  /v2-experimental/webhooks/board_subscriptions:
    post:
      description: Creates a webhook subscription to receive notifications when an
        item on a board is updated. Subscriptions are created per user, per board.
        You can create multiple subscriptions. We currently support all board items
        barring tags, connectors, and comments. Changes in item position do not trigger
        an event at the moment.<br/><h3>Required scope</h3> <a target="blank" href="/reference/scopes">boards:read</a>
        <br/><h3>Rate limiting</h3> <a target="blank" href="/reference/ratelimiting">Level
        2</a><br/>
      operationId: create-board-subscription
      summary: Create webhook subscription
      tags:
      - Webhooks (experimental)
  /v2-experimental/webhooks/board_subscriptions/{subscription_id}:
    patch:
      description: Updates the status or the callback URL of an existing webhook subscription.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-board-subscription
      summary: Update webhook subscription
      tags:
      - Webhooks (experimental)
  /v2-experimental/webhooks/subscriptions:
    get:
      description: Retrieves information about all webhook subscriptions for a specific
        user.<br/><h3>Required scope</h3> <a target="blank" href="/reference/scopes">boards:read</a>
        <br/><h3>Rate limiting</h3> <a target="blank" href="/reference/ratelimiting">Level
        4</a><br/>
      operationId: get-user-subscriptions
      summary: Get webhook subscriptions
      tags:
      - Webhooks (experimental)
  /v2-experimental/webhooks/subscriptions/{subscription_id}:
    get:
      description: Retrieves information for a specific webhook subscription.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: get-subscription-by-id
      summary: Get specific webhook subscription
      tags:
      - Webhooks (experimental)
    delete:
      description: Deletes the specified webhook subscription.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate limiting</h3>
        <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: delete-subscription-by-id
      summary: Delete webhook subscription
      tags:
      - Webhooks (experimental)
  /v2-experimental/boards/{board_id}/mindmap_nodes/{item_id}:
  /v2-experimental/boards/{board_id}/mindmap_nodes:
  /v2-experimental/boards/{board_id}/items:
    get:
      description: 'Retrieves a list of items for a specific board. You can retrieve
        all items on the board, a list of child items inside a parent item, or a list
        of specific types of items by specifying URL query parameter values.


        This method returns results using a cursor-based approach. A cursor-paginated
        method returns a portion of the total set of results based on the limit specified
        and a cursor that points to the next portion of the results. To retrieve the
        next portion of the collection, on your next call to the same method, set
        the `cursor` parameter equal to the `cursor` value you received in the response
        of the previous request. For example, if you set the `limit` query parameter
        to `10` and the board contains 20 objects, the first call will return information
        about the first 10 objects in the response along with a cursor parameter and
        value. In this example, let''s say the cursor parameter value returned in
        the response is `foo`. If you want to retrieve the next set of objects, on
        your next call to the same method, set the cursor parameter value to `foo`.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>'
      operationId: get-items-flowchart
      summary: Get items on board
      tags:
      - Flowchart shapes (experimental)
  /v2-experimental/boards/{board_id}/items/{item_id}:
    get:
      description: Retrieves information for a specific item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-specific-item-flowchart
      summary: Get specific item on board
      tags:
      - Flowchart shapes (experimental)
  /v2-experimental/boards/{board_id}/shapes:
    post:
      description: Adds a flowchart shape item to a board.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: create-shape-item-flowchart
      summary: Create shape item
      tags:
      - Flowchart shapes (experimental)
  /v2-experimental/boards/{board_id}/shapes/{item_id}:
    get:
      description: Retrieves information for a specific shape item on a board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:read</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 1</a><br/>
      operationId: get-shape-item-flowchart
      summary: Get shape item
      tags:
      - Flowchart shapes (experimental)
    patch:
      description: Updates a flowchart shape item on a board based on the data and
        style properties provided in the request body.<br/><h3>Required scope</h3>
        <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 2</a><br/>
      operationId: update-shape-item-flowchart
      summary: Update shape item
      tags:
      - Flowchart shapes (experimental)
    delete:
      description: Deletes a flowchart shape item from the board.<br/><h3>Required
        scope</h3> <a target="blank" href="/reference/scopes">boards:write</a> <br/><h3>Rate
        limiting</h3> <a target="blank" href="/reference/ratelimiting">Level 3</a><br/>
      operationId: delete-shape-item-flowchart
      summary: Delete shape item
      tags:
      - Flowchart shapes (experimental)
components:
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
