# coding: utf-8

"""
Miro Developer Platform

<img src=\"https://content.pstmn.io/47449ea6-0ef7-4af2-bac1-e58a70e61c58/aW1hZ2UucG5n\" width=\"1685\" height=\"593\">  ### Miro Developer Platform concepts  - New to the Miro Developer Platform? Interested in learning more about platform concepts?? [Read our introduction page](https://beta.developers.miro.com/docs/introduction) and familiarize yourself with the Miro Developer Platform capabilities in a few minutes.   ### Getting started with the Miro REST API  - [Quickstart (video):](https://beta.developers.miro.com/docs/try-out-the-rest-api-in-less-than-3-minutes) try the REST API in less than 3 minutes. - [Quickstart (article):](https://beta.developers.miro.com/docs/build-your-first-hello-world-app-1) get started and try the REST API in less than 3 minutes.   ### Miro REST API tutorials  Check out our how-to articles with step-by-step instructions and code examples so you can:  - [Get started with OAuth 2.0 and Miro](https://beta.developers.miro.com/docs/getting-started-with-oauth)   ### Miro App Examples  Clone our [Miro App Examples repository](https://github.com/miroapp/app-examples) to get inspiration, customize, and explore apps built on top of Miro's Developer Platform 2.0.

The version of the OpenAPI document: v2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from miro_api.models.ai_interaction_log_actor import AiInteractionLogActor
from miro_api.models.ai_interaction_log_model import AiInteractionLogModel
from miro_api.models.ai_interaction_log_object import AiInteractionLogObject
from miro_api.models.ai_interaction_log_session import AiInteractionLogSession
from miro_api.models.ai_interaction_log_tool import AiInteractionLogTool
from typing import Optional, Set
from typing_extensions import Self


class AiInteractionLog(BaseModel):
    """
    Contains information about a single AI interaction event. One conversation produces several events that share the same <code>session.id</code>, and one request together with its response share the same <code>turnId</code>.
    """  # noqa: E501

    id: Optional[StrictStr] = Field(default=None, description="Unique identifier of the AI interaction log entry.")
    created_at: Optional[datetime] = Field(
        default=None,
        description="Date and time when the AI interaction occurred.<br>Format: UTC, adheres to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), includes a [trailing Z offset](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)). ",
        alias="createdAt",
    )
    stored_at: Optional[datetime] = Field(
        default=None,
        description="Date and time when the AI interaction log was stored.<br>Format: UTC, adheres to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), includes a [trailing Z offset](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)). ",
        alias="storedAt",
    )
    session: Optional[AiInteractionLogSession] = None
    surface: Optional[StrictStr] = Field(
        default=None,
        description="Where in Miro the interaction started: the entry point the user acted through, for example Sidekick chat, an AI Flow, or an MCP call. It is not the AI capability that ran, since one surface can invoke many features. Events not yet attributed to a specific surface arrive as <code>unspecified</code>. Read it as a string rather than a fixed list, because values are added as more entry points are covered. ",
    )
    actor: Optional[AiInteractionLogActor] = None
    object: Optional[AiInteractionLogObject] = None
    event_type: Optional[StrictStr] = Field(
        default=None,
        description="Step of the interaction this entry records: <ul> <li><code>input</code>: the request that opened the turn, as received, before any processing. In a conversation this is the person's prompt; for automated features it is the request that triggered the work.</li> <li><code>model_invocation_request</code>: what was sent to the model, including context and conversation history the AI added.</li> <li><code>model_invocation_response</code>: what the model returned.</li> <li><code>tool_invocation_request</code>: a tool the AI decided to call, and the arguments it passed.</li> <li><code>tool_invocation_response</code>: the outcome of that tool call.</li> <li><code>output</code>: the final response returned for that request. In a conversation this is what the person was shown.</li> </ul> Not all events are produced for every interaction: some carry only model events, some only tool events. New event types may be added, so ignore a type you do not recognise rather than treating it as an error. ",
        alias="eventType",
    )
    turn_id: Optional[StrictStr] = Field(
        default=None,
        description="Groups the events of one exchange: a single user request, everything the AI did to handle it (model calls and tool calls), and the response returned to the user. A conversation is a sequence of turns; every event of one turn shares a <code>turnId</code>. ",
        alias="turnId",
    )
    details: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional details about the AI interaction. The structure of this object varies depending on the event type. The text may contain unstructured data that could reveal information used in interactions with the LLM. The example below is a <code>model_invocation_response</code>.",
    )
    model: Optional[AiInteractionLogModel] = None
    tool: Optional[AiInteractionLogTool] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "id",
        "createdAt",
        "storedAt",
        "session",
        "surface",
        "actor",
        "object",
        "eventType",
        "turnId",
        "details",
        "model",
        "tool",
    ]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AiInteractionLog from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict["session"] = self.session.to_dict()
        # override the default output from pydantic by calling `to_dict()` of actor
        if self.actor:
            _dict["actor"] = self.actor.to_dict()
        # override the default output from pydantic by calling `to_dict()` of object
        if self.object:
            _dict["object"] = self.object.to_dict()
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict["model"] = self.model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tool
        if self.tool:
            _dict["tool"] = self.tool.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AiInteractionLog from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "createdAt": obj.get("createdAt"),
                "storedAt": obj.get("storedAt"),
                "session": (
                    AiInteractionLogSession.from_dict(obj["session"]) if obj.get("session") is not None else None
                ),
                "surface": obj.get("surface"),
                "actor": AiInteractionLogActor.from_dict(obj["actor"]) if obj.get("actor") is not None else None,
                "object": AiInteractionLogObject.from_dict(obj["object"]) if obj.get("object") is not None else None,
                "eventType": obj.get("eventType"),
                "turnId": obj.get("turnId"),
                "details": obj.get("details"),
                "model": AiInteractionLogModel.from_dict(obj["model"]) if obj.get("model") is not None else None,
                "tool": AiInteractionLogTool.from_dict(obj["tool"]) if obj.get("tool") is not None else None,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
