# coding: utf-8

"""
Miro Developer Platform

<img src=\"https://content.pstmn.io/47449ea6-0ef7-4af2-bac1-e58a70e61c58/aW1hZ2UucG5n\" width=\"1685\" height=\"593\">  ### Miro Developer Platform concepts  - New to the Miro Developer Platform? Interested in learning more about platform concepts?? [Read our introduction page](https://beta.developers.miro.com/docs/introduction) and familiarize yourself with the Miro Developer Platform capabilities in a few minutes.   ### Getting started with the Miro REST API  - [Quickstart (video):](https://beta.developers.miro.com/docs/try-out-the-rest-api-in-less-than-3-minutes) try the REST API in less than 3 minutes. - [Quickstart (article):](https://beta.developers.miro.com/docs/build-your-first-hello-world-app-1) get started and try the REST API in less than 3 minutes.   ### Miro REST API tutorials  Check out our how-to articles with step-by-step instructions and code examples so you can:  - [Get started with OAuth 2.0 and Miro](https://beta.developers.miro.com/docs/getting-started-with-oauth)   ### Miro App Examples  Clone our [Miro App Examples repository](https://github.com/miroapp/app-examples) to get inspiration, customize, and explore apps built on top of Miro's Developer Platform 2.0.

The version of the OpenAPI document: v2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class SchemaAttribute(BaseModel):
    """
    Definition of schema attributes.
    """  # noqa: E501

    schemas: Optional[List[StrictStr]] = Field(
        default=None,
        description="Identifies which schema(s) this resource used. In this case it is the SCIM core User/Group schema.",
    )
    name: Optional[StrictStr] = Field(default=None, description="Name of schema attribute.")
    type: Optional[StrictStr] = Field(default=None, description="Type of schema attribute.")
    multi_valued: Optional[StrictBool] = Field(
        default=None, description="Indicates whether the attribute is multi-valued.", alias="multiValued"
    )
    description: Optional[StrictStr] = Field(default=None, description="Description of schema attribute.")
    required: Optional[StrictBool] = Field(default=None, description="Indicates whether the attribute is required.")
    sub_attributes: Optional[List[SchemaAttribute]] = Field(default=None, alias="subAttributes")
    case_exact: Optional[StrictBool] = Field(
        default=None, description="Indicates whether the attribute is case exact.", alias="caseExact"
    )
    mutability: Optional[StrictStr] = Field(default=None, description="Indicates the mutability of the attribute.")
    returned: Optional[StrictStr] = Field(
        default=None, description="Indicates when the attribute is returned in a response."
    )
    uniqueness: Optional[StrictStr] = Field(default=None, description="Indicates the uniqueness of the attribute.")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = [
        "schemas",
        "name",
        "type",
        "multiValued",
        "description",
        "required",
        "subAttributes",
        "caseExact",
        "mutability",
        "returned",
        "uniqueness",
    ]

    @field_validator("schemas")
    def schemas_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(["urn:ietf:params:scim:schemas:core:2.0:User"]):
                raise ValueError("each list item must be one of ('urn:ietf:params:scim:schemas:core:2.0:User')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SchemaAttribute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sub_attributes (list)
        _items = []
        if self.sub_attributes:
            for _item in self.sub_attributes:
                if _item:
                    _items.append(_item.to_dict())
            _dict["subAttributes"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SchemaAttribute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "schemas": obj.get("schemas"),
                "name": obj.get("name"),
                "type": obj.get("type"),
                "multiValued": obj.get("multiValued"),
                "description": obj.get("description"),
                "required": obj.get("required"),
                "subAttributes": (
                    [SchemaAttribute.from_dict(_item) for _item in obj["subAttributes"]]
                    if obj.get("subAttributes") is not None
                    else None
                ),
                "caseExact": obj.get("caseExact"),
                "mutability": obj.get("mutability"),
                "returned": obj.get("returned"),
                "uniqueness": obj.get("uniqueness"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


# TODO: Rewrite to not use raise_errors
SchemaAttribute.model_rebuild(raise_errors=False)
