/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Contains applicable links for the board.
*/
export class BoardLinks {
    /**
    * Link to obtain information about the board members associated with the board.
    */
    'related'?: string;
    /**
    * Link to obtain information about the current board.
    */
    'self'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "related",
            "baseName": "related",
            "type": "string"
        },
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BoardLinks.attributeTypeMap;
    }
}

