/**
 * Miro API
 * Miro API
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FixedRatioNoRotationGeometry } from './fixedRatioNoRotationGeometry';
import { Parent } from './parent';
import { PositionChange } from './positionChange';
import { StickyNoteData } from './stickyNoteData';
import { StickyNoteStyle } from './stickyNoteStyle';

export class StickyNoteUpdateRequest {
    'data'?: StickyNoteData;
    'style'?: StickyNoteStyle;
    'position'?: PositionChange;
    'geometry'?: FixedRatioNoRotationGeometry;
    'parent'?: Parent;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "StickyNoteData"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "StickyNoteStyle"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "PositionChange"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "FixedRatioNoRotationGeometry"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "Parent"
        }    ];

    static getAttributeTypeMap() {
        return StickyNoteUpdateRequest.attributeTypeMap;
    }
}

