/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Contains information about the style of a sticky note item, such as the fill color or text alignment. For information about the JSON properties, see [Style](https://developers.miro.com/reference/style).
*/
export class StickyNoteStyle {
    /**
    * Fill color for the sticky note. Possible values: `gray`, `light_yellow`, `yellow`, `orange`, `light_green`, `green`, `dark_green`, `cyan`, `light_pink`, `pink`, `violet`, `red`, `light_blue`, `blue`, `dark_blue`, `black`
    */
    'fillColor'?: StickyNoteStyle.FillColorEnum = StickyNoteStyle.FillColorEnum.LightYellow;
    /**
    * Defines how the sticky note text is horizontally aligned. Possible values: `left`, `right`, `center`
    */
    'textAlign'?: StickyNoteStyle.TextAlignEnum = StickyNoteStyle.TextAlignEnum.Center;
    /**
    * Defines how the sticky note text is vertically aligned. Possible values: `top`, `middle`, `bottom`
    */
    'textAlignVertical'?: StickyNoteStyle.TextAlignVerticalEnum = StickyNoteStyle.TextAlignVerticalEnum.Top;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fillColor",
            "baseName": "fillColor",
            "type": "StickyNoteStyle.FillColorEnum"
        },
        {
            "name": "textAlign",
            "baseName": "textAlign",
            "type": "StickyNoteStyle.TextAlignEnum"
        },
        {
            "name": "textAlignVertical",
            "baseName": "textAlignVertical",
            "type": "StickyNoteStyle.TextAlignVerticalEnum"
        }    ];

    static getAttributeTypeMap() {
        return StickyNoteStyle.attributeTypeMap;
    }
}

export namespace StickyNoteStyle {
    export enum FillColorEnum {
        Gray = <any> 'gray',
        LightYellow = <any> 'light_yellow',
        Yellow = <any> 'yellow',
        Orange = <any> 'orange',
        LightGreen = <any> 'light_green',
        Green = <any> 'green',
        DarkGreen = <any> 'dark_green',
        Cyan = <any> 'cyan',
        LightPink = <any> 'light_pink',
        Pink = <any> 'pink',
        Violet = <any> 'violet',
        Red = <any> 'red',
        LightBlue = <any> 'light_blue',
        Blue = <any> 'blue',
        DarkBlue = <any> 'dark_blue',
        Black = <any> 'black'
    }
    export enum TextAlignEnum {
        Left = <any> 'left',
        Right = <any> 'right',
        Center = <any> 'center'
    }
    export enum TextAlignVerticalEnum {
        Top = <any> 'top',
        Middle = <any> 'middle',
        Bottom = <any> 'bottom'
    }
}
