/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreatePictureRequest } from './createPictureRequest';

export class TeamChanges {
    /**
    * Team name
    */
    'name'?: string;
    'picture'?: CreatePictureRequest;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "picture",
            "baseName": "picture",
            "type": "CreatePictureRequest"
        }    ];

    static getAttributeTypeMap() {
        return TeamChanges.attributeTypeMap;
    }
}

