/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserSchemaUrnIetfParamsScimSchemasExtensionEnterprise20UserManager } from './userSchemaUrnIetfParamsScimSchemasExtensionEnterprise20UserManager';

export class UserSchemaUrnIetfParamsScimSchemasExtensionEnterprise20User {
    'costCenter'?: string;
    'department'?: string;
    'division'?: string;
    'employeeNumber'?: string;
    'manager'?: UserSchemaUrnIetfParamsScimSchemasExtensionEnterprise20UserManager;
    'organization'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "costCenter",
            "baseName": "costCenter",
            "type": "string"
        },
        {
            "name": "department",
            "baseName": "department",
            "type": "string"
        },
        {
            "name": "division",
            "baseName": "division",
            "type": "string"
        },
        {
            "name": "employeeNumber",
            "baseName": "employeeNumber",
            "type": "string"
        },
        {
            "name": "manager",
            "baseName": "manager",
            "type": "UserSchemaUrnIetfParamsScimSchemasExtensionEnterprise20UserManager"
        },
        {
            "name": "organization",
            "baseName": "organization",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserSchemaUrnIetfParamsScimSchemasExtensionEnterprise20User.attributeTypeMap;
    }
}

