"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.AppCardStyle = void 0;
/**
* Contains information about the style of an app card item, such as the fill color. For information about the JSON properties, see [Style](https://developers.miro.com/reference/style).
*/
var AppCardStyle = /** @class */ (function () {
    function AppCardStyle() {
    }
    AppCardStyle.getAttributeTypeMap = function () {
        return AppCardStyle.attributeTypeMap;
    };
    AppCardStyle.discriminator = undefined;
    AppCardStyle.attributeTypeMap = [
        {
            "name": "fillColor",
            "baseName": "fillColor",
            "type": "string"
        }
    ];
    return AppCardStyle;
}());
exports.AppCardStyle = AppCardStyle;
