"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.AppCardUpdateRequest = void 0;
var AppCardUpdateRequest = /** @class */ (function () {
    function AppCardUpdateRequest() {
    }
    AppCardUpdateRequest.getAttributeTypeMap = function () {
        return AppCardUpdateRequest.attributeTypeMap;
    };
    AppCardUpdateRequest.discriminator = undefined;
    AppCardUpdateRequest.attributeTypeMap = [
        {
            "name": "data",
            "baseName": "data",
            "type": "AppCardDataChanges"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "AppCardStyle"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "PositionChange"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "Geometry"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "Parent"
        }
    ];
    return AppCardUpdateRequest;
}());
exports.AppCardUpdateRequest = AppCardUpdateRequest;
