"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.BoardChanges = void 0;
var BoardChanges = /** @class */ (function () {
    function BoardChanges() {
        /**
        * Name for the board.
        */
        this['name'] = 'Untitled';
    }
    BoardChanges.getAttributeTypeMap = function () {
        return BoardChanges.attributeTypeMap;
    };
    BoardChanges.discriminator = undefined;
    BoardChanges.attributeTypeMap = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "policy",
            "baseName": "policy",
            "type": "BoardPolicyChange"
        },
        {
            "name": "teamId",
            "baseName": "teamId",
            "type": "string"
        }
    ];
    return BoardChanges;
}());
exports.BoardChanges = BoardChanges;
