"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.BoardWithLinks = void 0;
var BoardWithLinks = /** @class */ (function () {
    function BoardWithLinks() {
    }
    BoardWithLinks.getAttributeTypeMap = function () {
        return BoardWithLinks.attributeTypeMap;
    };
    BoardWithLinks.discriminator = undefined;
    BoardWithLinks.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "Team"
        },
        {
            "name": "picture",
            "baseName": "picture",
            "type": "Picture"
        },
        {
            "name": "policy",
            "baseName": "policy",
            "type": "BoardPolicy"
        },
        {
            "name": "viewLink",
            "baseName": "viewLink",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "UserInfoShort"
        },
        {
            "name": "currentUserMembership",
            "baseName": "currentUserMembership",
            "type": "BoardMember"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "UserInfoShort"
        },
        {
            "name": "modifiedAt",
            "baseName": "modifiedAt",
            "type": "Date"
        },
        {
            "name": "modifiedBy",
            "baseName": "modifiedBy",
            "type": "UserInfoShort"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "BoardLinks"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return BoardWithLinks;
}());
exports.BoardWithLinks = BoardWithLinks;
