"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CardCreateRequest = void 0;
var CardCreateRequest = /** @class */ (function () {
    function CardCreateRequest() {
    }
    CardCreateRequest.getAttributeTypeMap = function () {
        return CardCreateRequest.attributeTypeMap;
    };
    CardCreateRequest.discriminator = undefined;
    CardCreateRequest.attributeTypeMap = [
        {
            "name": "data",
            "baseName": "data",
            "type": "CardData"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "CardStyle"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "PositionChange"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "Geometry"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "Parent"
        }
    ];
    return CardCreateRequest;
}());
exports.CardCreateRequest = CardCreateRequest;
