"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.CreateGroupRequest = void 0;
var CreateGroupRequest = /** @class */ (function () {
    function CreateGroupRequest() {
    }
    CreateGroupRequest.getAttributeTypeMap = function () {
        return CreateGroupRequest.attributeTypeMap;
    };
    CreateGroupRequest.discriminator = undefined;
    CreateGroupRequest.attributeTypeMap = [
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<GroupMember>"
        }
    ];
    return CreateGroupRequest;
}());
exports.CreateGroupRequest = CreateGroupRequest;
