"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.DocumentCreateRequest = void 0;
var DocumentCreateRequest = /** @class */ (function () {
    function DocumentCreateRequest() {
    }
    DocumentCreateRequest.getAttributeTypeMap = function () {
        return DocumentCreateRequest.attributeTypeMap;
    };
    DocumentCreateRequest.discriminator = undefined;
    DocumentCreateRequest.attributeTypeMap = [
        {
            "name": "data",
            "baseName": "data",
            "type": "DocumentUrlData"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "PositionChange"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "FixedRatioGeometry"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "Parent"
        }
    ];
    return DocumentCreateRequest;
}());
exports.DocumentCreateRequest = DocumentCreateRequest;
