"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.EmbedUrlDataChanges = void 0;
/**
* For information about the JSON properties, see [Data](https://developers.miro.com/reference/data).
*/
var EmbedUrlDataChanges = /** @class */ (function () {
    function EmbedUrlDataChanges() {
    }
    EmbedUrlDataChanges.getAttributeTypeMap = function () {
        return EmbedUrlDataChanges.attributeTypeMap;
    };
    EmbedUrlDataChanges.discriminator = undefined;
    EmbedUrlDataChanges.attributeTypeMap = [
        {
            "name": "mode",
            "baseName": "mode",
            "type": "EmbedUrlDataChanges.ModeEnum"
        },
        {
            "name": "previewUrl",
            "baseName": "previewUrl",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }
    ];
    return EmbedUrlDataChanges;
}());
exports.EmbedUrlDataChanges = EmbedUrlDataChanges;
(function (EmbedUrlDataChanges) {
    var ModeEnum;
    (function (ModeEnum) {
        ModeEnum[ModeEnum["Inline"] = 'inline'] = "Inline";
        ModeEnum[ModeEnum["Modal"] = 'modal'] = "Modal";
    })(ModeEnum = EmbedUrlDataChanges.ModeEnum || (EmbedUrlDataChanges.ModeEnum = {}));
})(EmbedUrlDataChanges = exports.EmbedUrlDataChanges || (exports.EmbedUrlDataChanges = {}));
exports.EmbedUrlDataChanges = EmbedUrlDataChanges;
