"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.FrameUpdateRequest = void 0;
var FrameUpdateRequest = /** @class */ (function () {
    function FrameUpdateRequest() {
    }
    FrameUpdateRequest.getAttributeTypeMap = function () {
        return FrameUpdateRequest.attributeTypeMap;
    };
    FrameUpdateRequest.discriminator = undefined;
    FrameUpdateRequest.attributeTypeMap = [
        {
            "name": "data",
            "baseName": "data",
            "type": "FrameChanges"
        },
        {
            "name": "style",
            "baseName": "style",
            "type": "FrameStyle"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "PositionChange"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "GeometryNoRotation"
        }
    ];
    return FrameUpdateRequest;
}());
exports.FrameUpdateRequest = FrameUpdateRequest;
