/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* Test error obj
*/
export declare class GetBoards400Response {
    /**
    * Code of the error
    */
    'code'?: string;
    /**
    * Description of the error
    */
    'message'?: string;
    /**
    * Status code of the error
    */
    'status'?: number;
    /**
    * Type of the error
    */
    'type'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
