"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.GroupListResponseAllOf = void 0;
var GroupListResponseAllOf = /** @class */ (function () {
    function GroupListResponseAllOf() {
    }
    GroupListResponseAllOf.getAttributeTypeMap = function () {
        return GroupListResponseAllOf.attributeTypeMap;
    };
    GroupListResponseAllOf.discriminator = undefined;
    GroupListResponseAllOf.attributeTypeMap = [
        {
            "name": "resources",
            "baseName": "Resources",
            "type": "Array<GroupSchema>"
        }
    ];
    return GroupListResponseAllOf;
}());
exports.GroupListResponseAllOf = GroupListResponseAllOf;
