"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ImageUpdateRequest = void 0;
var ImageUpdateRequest = /** @class */ (function () {
    function ImageUpdateRequest() {
    }
    ImageUpdateRequest.getAttributeTypeMap = function () {
        return ImageUpdateRequest.attributeTypeMap;
    };
    ImageUpdateRequest.discriminator = undefined;
    ImageUpdateRequest.attributeTypeMap = [
        {
            "name": "data",
            "baseName": "data",
            "type": "ImageUrlDataChanges"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "PositionChange"
        },
        {
            "name": "geometry",
            "baseName": "geometry",
            "type": "FixedRatioGeometry"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "Parent"
        }
    ];
    return ImageUpdateRequest;
}());
exports.ImageUpdateRequest = ImageUpdateRequest;
