"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.ModifiedBy = void 0;
/**
* Contains information about the user who last modified the item.
*/
var ModifiedBy = /** @class */ (function () {
    function ModifiedBy() {
    }
    ModifiedBy.getAttributeTypeMap = function () {
        return ModifiedBy.attributeTypeMap;
    };
    ModifiedBy.discriminator = undefined;
    ModifiedBy.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return ModifiedBy;
}());
exports.ModifiedBy = ModifiedBy;
