/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare class Organization {
    /**
    * Purchased FULL licenses
    */
    'fullLicensesPurchased'?: number;
    /**
    * Id of the organization
    */
    'id'?: string;
    /**
    * Name of the organization
    */
    'name'?: string;
    /**
    * Organization plan type
    */
    'plan'?: Organization.PlanEnum;
    'type'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
export declare namespace Organization {
    enum PlanEnum {
        Unknown,
        Company,
        Consultant,
        ConsultantSlf,
        Business,
        PaidTeamOrg,
        IntegrationOrg,
        Professional2022
    }
}
