"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.Organization = void 0;
var Organization = /** @class */ (function () {
    function Organization() {
    }
    Organization.getAttributeTypeMap = function () {
        return Organization.attributeTypeMap;
    };
    Organization.discriminator = undefined;
    Organization.attributeTypeMap = [
        {
            "name": "fullLicensesPurchased",
            "baseName": "fullLicensesPurchased",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "Organization.PlanEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return Organization;
}());
exports.Organization = Organization;
(function (Organization) {
    var PlanEnum;
    (function (PlanEnum) {
        PlanEnum[PlanEnum["Unknown"] = 'UNKNOWN'] = "Unknown";
        PlanEnum[PlanEnum["Company"] = 'COMPANY'] = "Company";
        PlanEnum[PlanEnum["Consultant"] = 'CONSULTANT'] = "Consultant";
        PlanEnum[PlanEnum["ConsultantSlf"] = 'CONSULTANT_SLF'] = "ConsultantSlf";
        PlanEnum[PlanEnum["Business"] = 'BUSINESS'] = "Business";
        PlanEnum[PlanEnum["PaidTeamOrg"] = 'PAID_TEAM_ORG'] = "PaidTeamOrg";
        PlanEnum[PlanEnum["IntegrationOrg"] = 'INTEGRATION_ORG'] = "IntegrationOrg";
        PlanEnum[PlanEnum["Professional2022"] = 'PROFESSIONAL_2022'] = "Professional2022";
    })(PlanEnum = Organization.PlanEnum || (Organization.PlanEnum = {}));
})(Organization = exports.Organization || (exports.Organization = {}));
exports.Organization = Organization;
