/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
* Contains information about the cover picture of the board.
*/
export declare class Picture {
    /**
    * Unique identifier (ID) of the cover picture for the board.
    */
    'id'?: number;
    /**
    * URL of the cover picture of the board.
    */
    'imageURL'?: string;
    /**
    * Original team picture url for icon generation
    */
    'originalUrl'?: string;
    'type'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
