"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.StickyNoteData = void 0;
/**
* Contains sticky note item data, such as the content or shape of the sticky note. For information about the JSON properties, see [Data](https://developers.miro.com/reference/data).
*/
var StickyNoteData = /** @class */ (function () {
    function StickyNoteData() {
        /**
        * The actual text (content) that appears in the sticky note item.
        */
        this['content'] = 'Hello';
        /**
        * Defines the geometric shape of the sticky note and aspect ratio for its dimensions. Possible values: `square`, `rectangle`
        */
        this['shape'] = StickyNoteData.ShapeEnum.Square;
    }
    StickyNoteData.getAttributeTypeMap = function () {
        return StickyNoteData.attributeTypeMap;
    };
    StickyNoteData.discriminator = undefined;
    StickyNoteData.attributeTypeMap = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "shape",
            "baseName": "shape",
            "type": "StickyNoteData.ShapeEnum"
        }
    ];
    return StickyNoteData;
}());
exports.StickyNoteData = StickyNoteData;
(function (StickyNoteData) {
    var ShapeEnum;
    (function (ShapeEnum) {
        ShapeEnum[ShapeEnum["Square"] = 'square'] = "Square";
        ShapeEnum[ShapeEnum["Rectangle"] = 'rectangle'] = "Rectangle";
    })(ShapeEnum = StickyNoteData.ShapeEnum || (StickyNoteData.ShapeEnum = {}));
})(StickyNoteData = exports.StickyNoteData || (exports.StickyNoteData = {}));
exports.StickyNoteData = StickyNoteData;
