"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.StickyNoteStyle = void 0;
/**
* Contains information about the style of a sticky note item, such as the fill color or text alignment. For information about the JSON properties, see [Style](https://developers.miro.com/reference/style).
*/
var StickyNoteStyle = /** @class */ (function () {
    function StickyNoteStyle() {
        /**
        * Fill color for the sticky note. Possible values: `gray`, `light_yellow`, `yellow`, `orange`, `light_green`, `green`, `dark_green`, `cyan`, `light_pink`, `pink`, `violet`, `red`, `light_blue`, `blue`, `dark_blue`, `black`
        */
        this['fillColor'] = StickyNoteStyle.FillColorEnum.LightYellow;
        /**
        * Defines how the sticky note text is horizontally aligned. Possible values: `left`, `right`, `center`
        */
        this['textAlign'] = StickyNoteStyle.TextAlignEnum.Center;
        /**
        * Defines how the sticky note text is vertically aligned. Possible values: `top`, `middle`, `bottom`
        */
        this['textAlignVertical'] = StickyNoteStyle.TextAlignVerticalEnum.Top;
    }
    StickyNoteStyle.getAttributeTypeMap = function () {
        return StickyNoteStyle.attributeTypeMap;
    };
    StickyNoteStyle.discriminator = undefined;
    StickyNoteStyle.attributeTypeMap = [
        {
            "name": "fillColor",
            "baseName": "fillColor",
            "type": "StickyNoteStyle.FillColorEnum"
        },
        {
            "name": "textAlign",
            "baseName": "textAlign",
            "type": "StickyNoteStyle.TextAlignEnum"
        },
        {
            "name": "textAlignVertical",
            "baseName": "textAlignVertical",
            "type": "StickyNoteStyle.TextAlignVerticalEnum"
        }
    ];
    return StickyNoteStyle;
}());
exports.StickyNoteStyle = StickyNoteStyle;
(function (StickyNoteStyle) {
    var FillColorEnum;
    (function (FillColorEnum) {
        FillColorEnum[FillColorEnum["Gray"] = 'gray'] = "Gray";
        FillColorEnum[FillColorEnum["LightYellow"] = 'light_yellow'] = "LightYellow";
        FillColorEnum[FillColorEnum["Yellow"] = 'yellow'] = "Yellow";
        FillColorEnum[FillColorEnum["Orange"] = 'orange'] = "Orange";
        FillColorEnum[FillColorEnum["LightGreen"] = 'light_green'] = "LightGreen";
        FillColorEnum[FillColorEnum["Green"] = 'green'] = "Green";
        FillColorEnum[FillColorEnum["DarkGreen"] = 'dark_green'] = "DarkGreen";
        FillColorEnum[FillColorEnum["Cyan"] = 'cyan'] = "Cyan";
        FillColorEnum[FillColorEnum["LightPink"] = 'light_pink'] = "LightPink";
        FillColorEnum[FillColorEnum["Pink"] = 'pink'] = "Pink";
        FillColorEnum[FillColorEnum["Violet"] = 'violet'] = "Violet";
        FillColorEnum[FillColorEnum["Red"] = 'red'] = "Red";
        FillColorEnum[FillColorEnum["LightBlue"] = 'light_blue'] = "LightBlue";
        FillColorEnum[FillColorEnum["Blue"] = 'blue'] = "Blue";
        FillColorEnum[FillColorEnum["DarkBlue"] = 'dark_blue'] = "DarkBlue";
        FillColorEnum[FillColorEnum["Black"] = 'black'] = "Black";
    })(FillColorEnum = StickyNoteStyle.FillColorEnum || (StickyNoteStyle.FillColorEnum = {}));
    var TextAlignEnum;
    (function (TextAlignEnum) {
        TextAlignEnum[TextAlignEnum["Left"] = 'left'] = "Left";
        TextAlignEnum[TextAlignEnum["Right"] = 'right'] = "Right";
        TextAlignEnum[TextAlignEnum["Center"] = 'center'] = "Center";
    })(TextAlignEnum = StickyNoteStyle.TextAlignEnum || (StickyNoteStyle.TextAlignEnum = {}));
    var TextAlignVerticalEnum;
    (function (TextAlignVerticalEnum) {
        TextAlignVerticalEnum[TextAlignVerticalEnum["Top"] = 'top'] = "Top";
        TextAlignVerticalEnum[TextAlignVerticalEnum["Middle"] = 'middle'] = "Middle";
        TextAlignVerticalEnum[TextAlignVerticalEnum["Bottom"] = 'bottom'] = "Bottom";
    })(TextAlignVerticalEnum = StickyNoteStyle.TextAlignVerticalEnum || (StickyNoteStyle.TextAlignVerticalEnum = {}));
})(StickyNoteStyle = exports.StickyNoteStyle || (exports.StickyNoteStyle = {}));
exports.StickyNoteStyle = StickyNoteStyle;
