"use strict";
/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
exports.__esModule = true;
exports.TeamInvitationSettings = void 0;
/**
* Team invitation settings
*/
var TeamInvitationSettings = /** @class */ (function () {
    function TeamInvitationSettings() {
    }
    TeamInvitationSettings.getAttributeTypeMap = function () {
        return TeamInvitationSettings.attributeTypeMap;
    };
    TeamInvitationSettings.discriminator = undefined;
    TeamInvitationSettings.attributeTypeMap = [
        {
            "name": "inviteExternalUsers",
            "baseName": "inviteExternalUsers",
            "type": "TeamInvitationSettings.InviteExternalUsersEnum"
        },
        {
            "name": "whoCanInvite",
            "baseName": "whoCanInvite",
            "type": "TeamInvitationSettings.WhoCanInviteEnum"
        }
    ];
    return TeamInvitationSettings;
}());
exports.TeamInvitationSettings = TeamInvitationSettings;
(function (TeamInvitationSettings) {
    var InviteExternalUsersEnum;
    (function (InviteExternalUsersEnum) {
        InviteExternalUsersEnum[InviteExternalUsersEnum["Allowed"] = 'allowed'] = "Allowed";
        InviteExternalUsersEnum[InviteExternalUsersEnum["NotAllowed"] = 'not_allowed'] = "NotAllowed";
    })(InviteExternalUsersEnum = TeamInvitationSettings.InviteExternalUsersEnum || (TeamInvitationSettings.InviteExternalUsersEnum = {}));
    var WhoCanInviteEnum;
    (function (WhoCanInviteEnum) {
        WhoCanInviteEnum[WhoCanInviteEnum["OnlyOrgAdmins"] = 'only_org_admins'] = "OnlyOrgAdmins";
        WhoCanInviteEnum[WhoCanInviteEnum["Admins"] = 'admins'] = "Admins";
        WhoCanInviteEnum[WhoCanInviteEnum["AllMembers"] = 'all_members'] = "AllMembers";
    })(WhoCanInviteEnum = TeamInvitationSettings.WhoCanInviteEnum || (TeamInvitationSettings.WhoCanInviteEnum = {}));
})(TeamInvitationSettings = exports.TeamInvitationSettings || (exports.TeamInvitationSettings = {}));
exports.TeamInvitationSettings = TeamInvitationSettings;
