/**
 * Platform Tags
 * SCIM V1 API implemented by Miro
 *
 * The version of the OpenAPI document: v2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TeamAccountDiscoverySettingsChanges } from './teamAccountDiscoverySettingsChanges';
import { TeamCollaborationSettingsChanges } from './teamCollaborationSettingsChanges';
import { TeamCopyAccessLevelSettingsChanges } from './teamCopyAccessLevelSettingsChanges';
import { TeamInvitationSettingsChanges } from './teamInvitationSettingsChanges';
import { TeamSharingPolicySettingsChanges } from './teamSharingPolicySettingsChanges';
export declare class TeamSettingsChanges {
    'teamAccountDiscoverySettings'?: TeamAccountDiscoverySettingsChanges;
    'teamCollaborationSettings'?: TeamCollaborationSettingsChanges;
    'teamCopyAccessLevelSettings'?: TeamCopyAccessLevelSettingsChanges;
    'teamInvitationSettings'?: TeamInvitationSettingsChanges;
    'teamSharingPolicySettings'?: TeamSharingPolicySettingsChanges;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
