{
  "openapi": "3.0.1",
  "info": {
    "description": "Miro API",
    "title": "Miro API",
    "version": "0.1"
  },
  "servers": [
    {
      "url": "https://api.miro.com/"
    }
  ],
  "paths": {
    "/v1/oauth/revoke": {
      "post": {
        "tags": ["tokens"],
        "summary": "Revoke token",
        "description": "Revoke the current access token. Revoking an access token means that the access token will no longer work. When an access token is revoked, the refresh token is also revoked and no longer valid. This does not uninstall the application for the user.",
        "operationId": "revoke-token"
      }
    },
    "/v1/oauth-token": {
      "get": {
        "tags": ["tokens"],
        "summary": "Get access token information",
        "description": "Get information about an access token, such as the token type, scopes, team, user, token creation date and time, and the user who created the token.",
        "operationId": "token-info"
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Creates an export job for one or more boards.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the[...]",
        "operationId": "enterprise-create-board-export",
        "summary": "Create board export job",
        "tags": ["Board export job"]
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs/{job_id}": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves the status of the board export job.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the[...]",
        "operationId": "enterprise-board-export-job-status",
        "summary": "Get board export job status",
        "tags": ["Board export job"]
      }
    },
    "/v2/orgs/{org_id}/boards/export/jobs/{job_id}/results": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves the result of the board export job. The response provides more information about the board export job, such as the S3 link to the files created.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:export</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/refere[...]",
        "operationId": "enterprise-board-export-job-results",
        "summary": "Get results for board export job",
        "tags": ["Board export job"]
      }
    },
    "/v2/orgs/{org_id}/content-logs/items": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves content changes for board items within your organization. Content changes are actions that users can perform on board items, such as updating a sticky note's text. You can retrieve results for a specific time period. You can also filter results based on the board IDs and the emails of users who created, modified, or deleted a board item. Additionally, results can be paginated for easier viewing and processing.\n<br/><h3>Required scope</h3> <a target=_blank href=[...]",
        "operationId": "enterprise-board-content-item-logs-fetch",
        "summary": "Retrieve content change logs of board items",
        "tags": ["Board Content Logs"]
      }
    },
    "/v2/orgs/{org_id}/data-classification-settings": {
      "get": {
        "description": "Retrieves board classification settings for an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use [...]",
        "operationId": "enterprise-dataclassification-organization-settings-get",
        "summary": "Get organization settings",
        "tags": ["Board classification: Organization level"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/data-classification": {
      "patch": {
        "description": "Updates board classification for not-classified only or all boards in an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You c[...]",
        "operationId": "enterprise-dataclassification-team-boards-bulk",
        "summary": "Bulk update boards classification",
        "tags": ["Board classification: Team level"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/data-classification-settings": {
      "get": {
        "description": "Retrieves board classification settings for an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use th[...]",
        "operationId": "enterprise-dataclassification-team-settings-get",
        "summary": "Get team settings",
        "tags": ["Board classification: Team level"]
      },
      "patch": {
        "description": "Updates board classification settings for an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use thi[...]",
        "operationId": "enterprise-dataclassification-team-settings-set",
        "summary": "Update team settings",
        "tags": ["Board classification: Team level"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/boards/{board_id}/data-classification": {
      "get": {
        "description": "Retrieves board classification for a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the rol[...]",
        "operationId": "enterprise-dataclassification-board-get",
        "summary": "Get board classification",
        "tags": ["Board classification: Board level"]
      },
      "post": {
        "description": "Updates board classification for an existing board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you hav[...]",
        "operationId": "enterprise-dataclassification-board-set",
        "summary": "Update board classification",
        "tags": ["Board classification: Board level"]
      }
    },
    "/v2/orgs/{org_id}": {
      "get": {
        "description": "Retrieves organization information.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role[...]",
        "operationId": "enterprise-get-organization",
        "summary": "Get organization info",
        "tags": ["Organizations"]
      }
    },
    "/v2/orgs/{org_id}/members": {
      "get": {
        "description": "Retrieves organization members based on the organization ID and the cursor, or based on the user emails provided in the request.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#ent[...]",
        "operationId": "enterprise-get-organization-members",
        "summary": "Get organization members",
        "tags": ["Organization Members"]
      }
    },
    "/v2/orgs/{org_id}/members/{member_id}": {
      "get": {
        "description": "Retrieves organization member information for an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only us[...]",
        "operationId": "enterprise-get-organization-member",
        "summary": "Get organization member",
        "tags": ["Organization Members"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects": {
      "post": {
        "description": "Projects are essentially folders of boards with the option to manage user access for a smaller group of people within a team. Projects are here to help you organize your boards and make them easier to find and share. In other words, a project is a group of boards that you can share with your teammates all at once. For more information, see our <a href=\"https://help.miro.com/hc/en-us/articles/360018262033-Projects\" target=_blank>Help Center page on Projects</a>. <br><br>[...]",
        "operationId": "enterprise-create-project",
        "summary": "Create project",
        "tags": ["Projects"]
      },
      "get": {
        "description": "Retrieves the list of projects in an existing team of an organization. You can retrieve all projects, including all private projects (projects that haven't been specifically shared with you) by enabling Content Admin permissions. To enable Content Admin permissions, see [Content Admin permissions for Company Admins](https://help.miro.com/hc/en-us/articles/360012777280-Content-Admin-permissions-for-Company-Admins).<br/><h3>Required scope</h3> <a target=_blank href=https://[...]",
        "operationId": "enterprise-get-projects",
        "summary": "List of projects",
        "tags": ["Projects"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}": {
      "get": {
        "description": "Retrieves project information, such as a name for an existing project.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this[...]",
        "operationId": "enterprise-get-project",
        "summary": "Get project",
        "tags": ["Projects"]
      },
      "patch": {
        "description": "Update information about a project, such as the project name.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoin[...]",
        "operationId": "enterprise-update-project",
        "summary": "Update project",
        "tags": ["Projects"]
      },
      "delete": {
        "description": "Deletes a project. After a project is deleted, all boards and users that belong to the project remain in the team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Ent[...]",
        "operationId": "enterprise-delete-project",
        "summary": "Delete project",
        "tags": ["Projects"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}/settings": {
      "get": {
        "description": "Retrieves the project settings.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of a Com[...]",
        "operationId": "enterprise-get-project-settings",
        "summary": "Get project settings",
        "tags": ["Project Settings"]
      },
      "patch": {
        "description": "Updates the settings of a project.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of a[...]",
        "operationId": "enterprise-update-project-settings",
        "summary": "Update project settings",
        "tags": ["Project Settings"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}/members": {
      "post": {
        "description": "Add a Miro user to a project.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of a Comp[...]",
        "operationId": "enterprise-add-project-member",
        "summary": "Add member in a project",
        "tags": ["Project Members"]
      },
      "get": {
        "description": "Retrieves the list of members for a specific project.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you [...]",
        "operationId": "enterprise-get-project-members",
        "summary": "List of project members",
        "tags": ["Project Members"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}/members/{member_id}": {
      "get": {
        "description": "Retrieves information for a specific project member.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you h[...]",
        "operationId": "enterprise-get-project-member",
        "summary": "Get project member",
        "tags": ["Project Members"]
      },
      "patch": {
        "description": "Updates details of a project member, such as the member's role.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpo[...]",
        "operationId": "enterprise-update-project-member",
        "summary": "Update project member",
        "tags": ["Project Members"]
      },
      "delete": {
        "description": "Remove a member from a project. The user remains in the team even after the member is removed from a project.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>projects:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterpri[...]",
        "operationId": "enterprise-delete-project-member",
        "summary": "Remove project member",
        "tags": ["Project Members"]
      }
    },
    "/v2/orgs/{org_id}/teams": {
      "post": {
        "description": "Creates a new team in an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint i[...]",
        "operationId": "enterprise-create-team",
        "summary": "Create team",
        "tags": ["Teams"]
      },
      "get": {
        "description": "Retrieves list of teams in an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoi[...]",
        "operationId": "enterprise-get-teams",
        "summary": "List teams",
        "tags": ["Teams"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}": {
      "get": {
        "description": "Retrieves team information for an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint i[...]",
        "operationId": "enterprise-get-team",
        "summary": "Get team",
        "tags": ["Teams"]
      },
      "patch": {
        "description": "Updates an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of[...]",
        "operationId": "enterprise-update-team",
        "summary": "Update team",
        "tags": ["Teams"]
      },
      "delete": {
        "description": "Deletes an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of[...]",
        "operationId": "enterprise-delete-team",
        "summary": "Delete team",
        "tags": ["Teams"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/members": {
      "post": {
        "description": "Invites a new Miro user to an existing team. The user must exist in your Miro organization. Users who do not exist in your Miro organization can be invited to the team via [SCIM](https://developers.miro.com/docs/scim) and an external identity provider, such as Okta or Azure Active Directory.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://[...]",
        "operationId": "enterprise-invite-team-member",
        "summary": "Invite team members",
        "tags": ["Team Members"]
      },
      "get": {
        "description": "Retrieves team members by cursor.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the [...]",
        "operationId": "enterprise-get-team-members",
        "summary": "List team members",
        "tags": ["Team Members"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/members/{member_id}": {
      "get": {
        "description": "Retrieves team member by id.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role [...]",
        "operationId": "enterprise-get-team-member",
        "summary": "Get team member",
        "tags": ["Team Members"]
      },
      "patch": {
        "description": "Updates team member role in team by id.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you ha[...]",
        "operationId": "enterprise-update-team-member",
        "summary": "Update team member",
        "tags": ["Team Members"]
      },
      "delete": {
        "description": "Deletes team member from team by id.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have [...]",
        "operationId": "enterprise-delete-team-member",
        "summary": "Delete team member from team",
        "tags": ["Team Members"]
      }
    },
    "/v2/orgs/{org_id}/default_teams_settings": {
      "get": {
        "description": "Retrieves default team settings of an existing organization.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use thi[...]",
        "operationId": "enterprise-get-default-team-settings",
        "summary": "Get default team settings",
        "tags": ["Team Settings"]
      }
    },
    "/v2/orgs/{org_id}/teams/{team_id}/settings": {
      "get": {
        "description": "Retrieves team settings of an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if yo[...]",
        "operationId": "enterprise-get-team-settings",
        "summary": "Get team settings",
        "tags": ["Team Settings"]
      },
      "patch": {
        "description": "Updates team settings of an existing team.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>organizations:teams:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you[...]",
        "operationId": "enterprise-update-team-settings",
        "summary": "Update team settings",
        "tags": ["Team Settings"]
      }
    },
    "/v2/sessions/reset_all": {
      "post": {
        "description": "Delete all user sessions.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>sessions:delete</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a> <br/><h3>Enterprise only</h3> <p>This API is available only for <a target=_blank href=\"/reference/api-reference#enterprise-plan\">Enterprise plan</a> users. You can only use this endpoint if you have the role of a Company[...]",
        "operationId": "enterprise-post-user-sessions-reset",
        "summary": "Delete user sessions",
        "tags": ["User sessions"]
      }
    },
    "/v2-experimental/boards/{board_id}/items": {
    },
    "/v2/boards/{board_id}/frames": {
      "post": {
        "description": "Adds a frame to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-frame-item",
        "summary": "Create frame",
        "tags": ["frames"]
      }
    },
    "/v2/boards/{board_id}/frames/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific frame on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-frame-item",
        "summary": "Get frame",
        "tags": ["frames"]
      },
      "patch": {
        "description": "Updates a frame on a board based on the data, style, or geometry properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-frame-item",
        "summary": "Update frame",
        "tags": ["frames"]
      },
      "delete": {
        "description": "Deletes a frame from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-frame-item",
        "summary": "Delete frame",
        "tags": ["frames"]
      }
    },
    "/v2/boards/{board_id}/items": {
      "get": {
        "description": "Retrieves a list of items within a specific frame. A frame is a parent item and all items within a frame are child items. This method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor[...]",
        "operationId": "get-items-within-frame",
        "summary": "Get items within frame",
        "tags": ["items"]
      }
    },
    "/v2-experimental/webhooks/board_subscriptions": {
      "post": {
        "description": "Creates a webhook subscription to receive notifications when an item on a board is updated. Subscriptions are created per user, per board. You can create multiple subscriptions. We currently support all board items barring tags, connectors, and comments. Changes in item position do not trigger an event at the moment.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank h[...]",
        "operationId": "create-board-subscription",
        "summary": "Create webhook subscription",
        "tags": ["Webhooks (experimental)"]
      }
    },
    "/v2-experimental/webhooks/board_subscriptions/{subscription_id}": {
      "patch": {
        "description": "Updates the status or the callback URL of an existing webhook subscription.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-board-subscription",
        "summary": "Update webhook subscription",
        "tags": ["Webhooks (experimental)"]
      }
    },
    "/v2-experimental/webhooks/subscriptions": {
      "get": {
        "description": "Retrieves information about all webhook subscriptions for a specific user.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a><br/>",
        "operationId": "get-user-subscriptions",
        "summary": "Get webhook subscriptions",
        "tags": ["Webhooks (experimental)"]
      }
    },
    "/v2-experimental/webhooks/subscriptions/{subscription_id}": {
      "get": {
        "description": "Retrieves information for a specific webhook subscription.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "get-subscription-by-id",
        "summary": "Get specific webhook subscription",
        "tags": ["Webhooks (experimental)"]
      },
      "delete": {
        "description": "Deletes the specified webhook subscription.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "delete-subscription-by-id",
        "summary": "Delete webhook subscription",
        "tags": ["Webhooks (experimental)"]
      }
    },
    "/v2-experimental/boards/{board_id}/mindmap_nodes/{item_id}": {
      "get": {
        "x-settings": null,
        "description": "Retrieves information for a specific mind map node on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-mindmap-node-experimental",
        "summary": "Get specific mind map node",
        "tags": ["Mind map nodes (experimental)"]
      },
      "delete": {
        "x-settings": null,
        "description": "Deletes a mind map node item and its child nodes from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-mindmap-node-experimental",
        "summary": "Delete mind map node",
        "tags": ["Mind map nodes (experimental)"]
      }
    },
    "/v2-experimental/boards/{board_id}/mindmap_nodes": {
      "get": {
        "x-settings": null,
        "summary": "Get mind map nodes",
        "tags": ["Mind map nodes (experimental)"],
        "operationId": "get-mindmap-nodes-experimental",
        "description": "Retrieves a list of mind map nodes for a specific board.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor` value you received in the response of the previous request. [...]"
      },
      "post": {
        "x-settings": null,
        "description": "Adds a mind map node to a board. A root node is the starting point of a mind map. A node that is created under a root node is a child node. For information on mind maps, use cases, mind map structure, and more, see the <a href=\"https://developers.miro.com/docs/mind-maps\" target=_blank>Mind Map Overview</a> page. <br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank hr[...]",
        "operationId": "create-mindmap-nodes-experimental",
        "summary": "Create mind map node",
        "tags": ["Mind map nodes (experimental)"]
      }
    },
    "/v2-experimental/boards/{board_id}/items/{item_id}": {
      "get": {
        "x-settings": null,
        "description": "Retrieves information for a specific item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-specific-item-experimental",
        "summary": "Get specific item on board",
        "tags": ["Flowchart shapes (experimental)"]
      },
      "delete": {
        "x-settings": null,
        "description": "Deletes an item from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-item-experimental",
        "summary": "Delete item",
        "tags": ["items"]
      }
    },
    "/v2-experimental/boards/{board_id}/shapes": {
      "post": {
        "x-settings": null,
        "description": "Adds a flowchart shape item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-shape-item-flowchart",
        "summary": "Create shape item",
        "tags": ["Flowchart shapes (experimental)"]
      }
    },
    "/v2-experimental/boards/{board_id}/shapes/{item_id}": {
      "get": {
        "x-settings": null,
        "description": "Retrieves information for a specific shape item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-shape-item-flowchart",
        "summary": "Get shape item",
        "tags": ["Flowchart shapes (experimental)"]
      },
      "patch": {
        "x-settings": null,
        "description": "Updates a flowchart shape item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-shape-item-flowchart",
        "summary": "Update shape item",
        "tags": ["Flowchart shapes (experimental)"]
      },
      "delete": {
        "x-settings": null,
        "description": "Deletes a flowchart shape item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-shape-item-flowchart",
        "summary": "Delete shape item",
        "tags": ["Flowchart shapes (experimental)"]
      }
    },
    "/v2-experimental/boards/{board_id_PlatformExperimentalFeatures}/items": {
      "get": {
        "x-settings": null,
        "description": "Retrieves a list of items for a specific board. You can retrieve all items on the board, a list of child items inside a parent item, or a list of specific types of items by specifying URL query parameter values.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the coll[...]",
        "operationId": "get-items-experimental",
        "summary": "Get items on board",
        "tags": ["Flowchart shapes (experimental)"]
      }
    },
    "/v2-experimental/boards/{board_id}/items/bulk": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Adds different types of items to a board. You can add up to 20 items of the same or different type per create call. For example, you can create 3 shape items, 4 card items, and 5 sticky notes in one create call. The bulk create operation is transactional. If any item's create operation fails, the create operation for all the remaining items also fails, and none of the items will be created. <br/><br>To try out this API in our documentation:<br/><br>1. In the **BODY PARAMS[...]",
        "operationId": "create-items",
        "summary": "Create items in bulk"
      }
    },
    "/v2-experimental/boards/{board_id_PlatformBulkCreateOperationExperimentalRelease}/items": {
    },
    "/v2/boards/{board_id}/items/{item_id}": {
      "post": {
        "description": "Attach an existing tag to the specified item. Card and sticky note items can have up to 8 tags.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "attach-tag-to-item",
        "summary": "Attach tag to item",
        "tags": ["tags"]
      },
      "delete": {
        "description": "Removes the specified tag from the specified item. The tag still exists on the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "remove-tag-from-item",
        "summary": "Remove tag from item",
        "tags": ["tags"]
      }
    },
    "/v2/boards/{board_id}/items/{item_id}/tags": {
      "get": {
        "description": "Retrieves all the tags from the specified item.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-tags-from-item",
        "summary": "Get tags from item",
        "tags": ["tags"]
      }
    },
    "/v2/boards/{board_id}/tags": {
      "post": {
        "description": "Creates a tag on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "create-tag",
        "summary": "Create tag",
        "tags": ["tags"]
      },
      "get": {
        "description": "Retrieves all the tags from the specified board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-tags-from-board",
        "summary": "Get tags from board",
        "tags": ["tags"]
      }
    },
    "/v2/boards/{board_id}/tags/{tag_id}": {
      "get": {
        "description": "Retrieves information for a specific tag.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-tag",
        "summary": "Get tag",
        "tags": ["tags"]
      },
      "patch": {
        "description": "Updates a tag based on the data properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "update-tag",
        "summary": "Update tag",
        "tags": ["tags"]
      },
      "delete": {
        "description": "Deletes the specified tag from the board. The tag is also removed from all cards and sticky notes on the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "delete-tag",
        "summary": "Delete tag",
        "tags": ["tags"]
      }
    },
    "/v2/boards/{board_id_PlatformTags}/items": {
      "get": {
        "description": "Retrieves all the items that have the specified tag.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-items-by-tag",
        "summary": "Get items by tag",
        "tags": ["tags"]
      }
    },
    "/v2/boards": {
      "post": {
        "description": "Creates a board with the specified name and sharing policies.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "create-board",
        "summary": "Create board",
        "tags": ["boards"]
      },
      "get": {
        "description": "Retrieves a list of boards that match the search criteria provided in the request. If you are an Enterprise customer and a Company Admin, you can retrieve all boards, including all private boards (boards that haven't been specifically shared with you) by enabling Content Admin permissions. To enable Content Admin permissions, see [Content Admin permissions for Company Admins](https://help.miro.com/hc/en-us/articles/360012777280-Content-Admin-permissions-for-Company-Admins[...]",
        "operationId": "get-boards",
        "summary": "Get boards",
        "tags": ["boards"]
      },
      "put": {
        "description": "Creates a copy of an existing board. You can also update the name, description, sharing policy, and permissions policy for the new board in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 4</a><br/>",
        "operationId": "copy-board",
        "summary": "Copy board",
        "tags": ["boards"]
      }
    },
    "/v2/boards/{board_id}": {
      "get": {
        "description": "Retrieves information about a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-specific-board",
        "summary": "Get specific board",
        "tags": ["boards"]
      },
      "patch": {
        "description": "Updates a specific board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-board",
        "summary": "Update board",
        "tags": ["boards"]
      },
      "delete": {
        "description": "Deletes a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-board",
        "summary": "Delete board",
        "tags": ["boards"]
      }
    },
    "/v2/boards/{board_id}/app_cards": {
      "post": {
        "description": "Adds an app card item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-app-card-item",
        "summary": "Create app card item",
        "tags": ["app_cards"]
      }
    },
    "/v2/boards/{board_id}/app_cards/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific app card item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-app-card-item",
        "summary": "Get app card item",
        "tags": ["app_cards"]
      },
      "patch": {
        "description": "Updates an app card item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-app-card-item",
        "summary": "Update app card item",
        "tags": ["app_cards"]
      },
      "delete": {
        "description": "Deletes an app card item from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-app-card-item",
        "summary": "Delete app card item",
        "tags": ["app_cards"]
      }
    },
    "/v2/boards/{board_id}/cards": {
      "post": {
        "description": "Adds a card item to a board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-card-item",
        "summary": "Create card item",
        "tags": ["cards"]
      }
    },
    "/v2/boards/{board_id}/cards/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific card item on a board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-card-item",
        "summary": "Get card item",
        "tags": ["cards"]
      },
      "patch": {
        "description": "Updates a card item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-card-item",
        "summary": "Update card item",
        "tags": ["cards"]
      },
      "delete": {
        "description": "Deletes a card item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-card-item",
        "summary": "Delete card item",
        "tags": ["cards"]
      }
    },
    "/v2/boards/{board_id}/connectors": {
      "post": {
        "description": "Adds a connector to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-connector",
        "summary": "Create connector",
        "tags": ["connectors"]
      },
      "get": {
        "description": "Retrieves a list of connectors for a specific board.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the collection, on your next call to the same method, set the `cursor` parameter equal to the `cursor` value you received in the response of the previous request. For [...]",
        "operationId": "get-connectors",
        "summary": "Get connectors",
        "tags": ["connectors"]
      }
    },
    "/v2/boards/{board_id}/connectors/{connector_id}": {
      "get": {
        "description": "Retrieves information for a specific connector on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-connector",
        "summary": "Get specific connector",
        "tags": ["connectors"]
      },
      "patch": {
        "description": "Updates a connector on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-connector",
        "summary": "Update connector",
        "tags": ["connectors"]
      },
      "delete": {
        "description": "Deletes the specified connector from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-connector",
        "summary": "Delete connector",
        "tags": ["connectors"]
      }
    },
    "/v2/boards/{board_id}/documents": {
      "post": {
        "description": "Adds a document item to a board by specifying the URL where the document is hosted.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-document-item-using-url",
        "summary": "Create document item using URL",
        "tags": ["documents"]
      }
    },
    "/v2/boards/{board_id}/documents/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific document item on a board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-document-item",
        "summary": "Get document item",
        "tags": ["documents"]
      },
      "patch": {
        "description": "Updates a document item on a board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-document-item-using-url",
        "summary": "Update document item using URL",
        "tags": ["documents"]
      },
      "delete": {
        "description": "Deletes a document item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-document-item",
        "summary": "Delete document item",
        "tags": ["documents"]
      }
    },
    "/v2/boards/{board_id}/embeds": {
      "post": {
        "description": "Adds an embed item containing external content to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-embed-item",
        "summary": "Create embed item",
        "tags": ["embeds"]
      }
    },
    "/v2/boards/{board_id}/embeds/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific embed item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-embed-item",
        "summary": "Get embed item",
        "tags": ["embeds"]
      },
      "patch": {
        "description": "Updates an embed item on a board based on the data properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-embed-item",
        "summary": "Update embed item",
        "tags": ["embeds"]
      },
      "delete": {
        "description": "Deletes an embed item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-embed-item",
        "summary": "Delete embed item",
        "tags": ["embeds"]
      }
    },
    "/v2/boards/{board_id}/images": {
      "post": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Adds an image item to a board by specifying an image URL.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-image-item-using-url",
        "summary": "Create image item using URL",
        "tags": ["images"]
      }
    },
    "/v2/boards/{board_id}/images/{item_id}": {
      "get": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Retrieves information for a specific image item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-image-item",
        "summary": "Get image item",
        "tags": ["images"]
      },
      "patch": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Updates an image item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-image-item-using-url",
        "summary": "Update image item using URL",
        "tags": ["images"]
      },
      "delete": {
        "x-settings": {
          "skip-tests": true
        },
        "description": "Deletes an image item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-image-item",
        "summary": "Delete image item",
        "tags": ["images"]
      }
    },
    "/v2/boards/{board_id}/members": {
      "post": {
        "description": "Shares the board and Invites new members to collaborate on a board by sending an invitation email. Depending on the board's Sharing policy, there might be various scenarios where membership in the team is required in order to share the board with a user.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3<[...]",
        "operationId": "share-board",
        "summary": "Share board",
        "tags": ["board_members"]
      },
      "get": {
        "description": "Retrieves a pageable list of members for a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-board-members",
        "summary": "Get all board members",
        "tags": ["board_members"]
      }
    },
    "/v2/boards/{board_id}/members/{board_member_id}": {
      "get": {
        "description": "Retrieves information for a board member.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-specific-board-member",
        "summary": "Get specific board member",
        "tags": ["board_members"]
      },
      "patch": {
        "description": "Updates the role of a board member.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-board-member",
        "summary": "Update board member",
        "tags": ["board_members"]
      },
      "delete": {
        "description": "Removes a board member from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "remove-board-member",
        "summary": "Remove board member",
        "tags": ["board_members"]
      }
    },
    "/v2/boards/{board_id}/shapes": {
      "post": {
        "description": "Adds a shape item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-shape-item",
        "summary": "Create shape item",
        "tags": ["shapes"]
      }
    },
    "/v2/boards/{board_id}/shapes/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific shape item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-shape-item",
        "summary": "Get shape item",
        "tags": ["shapes"]
      },
      "patch": {
        "description": "Updates a shape item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-shape-item",
        "summary": "Update shape item",
        "tags": ["shapes"]
      },
      "delete": {
        "description": "Deletes a shape item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-shape-item",
        "summary": "Delete shape item",
        "tags": ["shapes"]
      }
    },
    "/v2/boards/{board_id}/sticky_notes": {
      "post": {
        "description": "Adds a sticky note item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-sticky-note-item",
        "summary": "Create sticky note item",
        "tags": ["sticky_notes"]
      }
    },
    "/v2/boards/{board_id}/sticky_notes/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific sticky note item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-sticky-note-item",
        "summary": "Get sticky note item",
        "tags": ["sticky_notes"]
      },
      "patch": {
        "description": "Updates a sticky note item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-sticky-note-item",
        "summary": "Update sticky note item",
        "tags": ["sticky_notes"]
      },
      "delete": {
        "description": "Deletes a sticky note item from the board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-sticky-note-item",
        "summary": "Delete sticky note item",
        "tags": ["sticky_notes"]
      }
    },
    "/v2/boards/{board_id}/texts": {
      "post": {
        "description": "Adds a text item to a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "create-text-item",
        "summary": "Create text item",
        "tags": ["texts"]
      }
    },
    "/v2/boards/{board_id}/texts/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific text item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-text-item",
        "summary": "Get text item",
        "tags": ["texts"]
      },
      "patch": {
        "description": "Updates a text item on a board based on the data and style properties provided in the request body.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-text-item",
        "summary": "Update text item",
        "tags": ["texts"]
      },
      "delete": {
        "description": "Deletes a text item from the board<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-text-item",
        "summary": "Delete text item",
        "tags": ["texts"]
      }
    },
    "/v2/boards/{board_id_Platform}/items": {
      "get": {
        "description": "Retrieves a list of items for a specific board. You can retrieve all items on the board, a list of child items inside a parent item, or a list of specific types of items by specifying URL query parameter values.\n\nThis method returns results using a cursor-based approach. A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor that points to the next portion of the results. To retrieve the next portion of the coll[...]",
        "operationId": "get-items",
        "summary": "Get items on board",
        "tags": ["items"]
      }
    },
    "/v2/boards/{board_id_Platform}/items/{item_id}": {
      "get": {
        "description": "Retrieves information for a specific item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:read</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 1</a><br/>",
        "operationId": "get-specific-item",
        "summary": "Get specific item on board",
        "tags": ["items"]
      },
      "patch": {
        "description": "Updates the position or the parent of an item on a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 2</a><br/>",
        "operationId": "update-item-position-or-parent",
        "summary": "Update item position or parent",
        "tags": ["items"]
      },
      "delete": {
        "description": "Deletes an item from a board.<br/><h3>Required scope</h3> <a target=_blank href=https://developers.miro.com/reference/scopes>boards:write</a> <br/><h3>Rate limiting</h3> <a target=_blank href=https://developers.miro.com/reference/ratelimiting>Level 3</a><br/>",
        "operationId": "delete-item",
        "summary": "Delete item",
        "tags": ["items"]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oAuth2AuthCode": {
        "type": "oauth2",
        "description": "For more information, see https://developers.miro.com/reference/authorization-flow-for-expiring-tokens",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://miro.com/oauth/authorize",
            "tokenUrl": "https://api.miro.com/v1/oauth/token",
            "scopes": {
              "boards:read": "Retrieve information about boards, board members, or items",
              "boards:write": "Create, update, or delete boards, board members, or items",
              "microphone:listen": "Access a user's microphone to record audio in an iFrame",
              "screen:record": "Access a user's screen to record it in an iFrame",
              "webcam:record": "Allows an iFrame to access a user's camera to record video",
              "organizations:read": "Read information about the organization, such as name, plan, number of licenses, organization settings, or organization members.",
              "organizations:teams:read": "Read team information, such as the list of teams, team settings, team members, for an organization.",
              "organizations:teams:write": "Create or delete teams, update team information, team settings, team members, for an organization."
            }
          }
        }
      }
    }
  }
}
