"""
    Miro Developer Platform

    <img src=\"https://content.pstmn.io/47449ea6-0ef7-4af2-bac1-e58a70e61c58/aW1hZ2UucG5n\" width=\"1685\" height=\"593\">  ### Miro Developer Platform concepts  - New to the Miro Developer Platform? Interested in learning more about platform concepts?? [Read our introduction page](https://beta.developers.miro.com/docs/introduction) and familiarize yourself with the Miro Developer Platform capabilities in a few minutes.   ### Getting started with the Miro REST API  - [Quickstart (video):](https://beta.developers.miro.com/docs/try-out-the-rest-api-in-less-than-3-minutes) try the REST API in less than 3 minutes. - [Quickstart (article):](https://beta.developers.miro.com/docs/build-your-first-hello-world-app-1) get started and try the REST API in less than 3 minutes.   ### Miro REST API tutorials  Check out our how-to articles with step-by-step instructions and code examples so you can:  - [Get started with OAuth 2.0 and Miro](https://beta.developers.miro.com/docs/getting-started-with-oauth)   ### Miro App Examples  Clone our [Miro App Examples repository](https://github.com/miroapp/app-examples) to get inspiration, customize, and explore apps built on top of Miro's Developer Platform 2.0.   # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import miro_api
from miro_api.model.created_by import CreatedBy
from miro_api.model.embed_data import EmbedData
from miro_api.model.geometry import Geometry
from miro_api.model.modified_by import ModifiedBy
from miro_api.model.parent_links_envelope import ParentLinksEnvelope
from miro_api.model.position import Position
from miro_api.model.widget_links import WidgetLinks
globals()['CreatedBy'] = CreatedBy
globals()['EmbedData'] = EmbedData
globals()['Geometry'] = Geometry
globals()['ModifiedBy'] = ModifiedBy
globals()['ParentLinksEnvelope'] = ParentLinksEnvelope
globals()['Position'] = Position
globals()['WidgetLinks'] = WidgetLinks
from miro_api.model.embed_item import EmbedItem


class TestEmbedItem(unittest.TestCase):
    """EmbedItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmbedItem(self):
        """Test EmbedItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmbedItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
