"""
    Miro Developer Platform

    <img src=\"https://content.pstmn.io/47449ea6-0ef7-4af2-bac1-e58a70e61c58/aW1hZ2UucG5n\" width=\"1685\" height=\"593\">  ### Miro Developer Platform concepts  - New to the Miro Developer Platform? Interested in learning more about platform concepts?? [Read our introduction page](https://beta.developers.miro.com/docs/introduction) and familiarize yourself with the Miro Developer Platform capabilities in a few minutes.   ### Getting started with the Miro REST API  - [Quickstart (video):](https://beta.developers.miro.com/docs/try-out-the-rest-api-in-less-than-3-minutes) try the REST API in less than 3 minutes. - [Quickstart (article):](https://beta.developers.miro.com/docs/build-your-first-hello-world-app-1) get started and try the REST API in less than 3 minutes.   ### Miro REST API tutorials  Check out our how-to articles with step-by-step instructions and code examples so you can:  - [Get started with OAuth 2.0 and Miro](https://beta.developers.miro.com/docs/getting-started-with-oauth)   ### Miro App Examples  Clone our [Miro App Examples repository](https://github.com/miroapp/app-examples) to get inspiration, customize, and explore apps built on top of Miro's Developer Platform 2.0.   # noqa: E501

    The version of the OpenAPI document: v2.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import miro_api
from miro_api.api.flowchart_shapes_experimental_api import FlowchartShapesExperimentalApi  # noqa: E501


class TestFlowchartShapesExperimentalApi(unittest.TestCase):
    """FlowchartShapesExperimentalApi unit test stubs"""

    def setUp(self):
        self.api = FlowchartShapesExperimentalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_shape_item_flowchart(self):
        """Test case for create_shape_item_flowchart

        Create shape item  # noqa: E501
        """
        pass

    def test_delete_shape_item_flowchart(self):
        """Test case for delete_shape_item_flowchart

        Delete shape item  # noqa: E501
        """
        pass

    def test_get_items_experimental(self):
        """Test case for get_items_experimental

        Get items on board  # noqa: E501
        """
        pass

    def test_get_shape_item_flowchart(self):
        """Test case for get_shape_item_flowchart

        Get shape item  # noqa: E501
        """
        pass

    def test_get_specific_item_experimental(self):
        """Test case for get_specific_item_experimental

        Get specific item on board  # noqa: E501
        """
        pass

    def test_update_shape_item_flowchart(self):
        """Test case for update_shape_item_flowchart

        Update shape item  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
